import 'dotenv/config'
import bcrypt from 'bcryptjs'
import prisma from '../src/utils/prisma.js'
import {
  deleteAppCategory,
  listAppCategories,
  reorderAppCategories,
  upsertAppCategory,
} from '../src/utils/appCategories.js'
import {
  deletePostCategory,
  listPostCategories,
  reorderPostCategories,
  upsertPostCategory,
} from '../src/utils/postCategories.js'

const SOFTWARE_RECOMMEND_CATEGORY = '软件推荐'

async function syncCategoryTables(appCategoryOrder: string[], postCategoryOrder: string[]) {
  for (const [index, name] of appCategoryOrder.entries()) {
    await upsertAppCategory(name, { sortOrder: index })
  }

  const currentAppCategories = await listAppCategories({ publishedOnly: false })
  for (const category of currentAppCategories) {
    if (!appCategoryOrder.includes(category.name) && Number(category.count || 0) === 0) {
      await deleteAppCategory(category.name)
    }
  }
  await reorderAppCategories(appCategoryOrder)

  for (const [index, name] of postCategoryOrder.entries()) {
    await upsertPostCategory(name, { sortOrder: index })
  }

  const currentPostCategories = await listPostCategories({ publishedOnly: false })
  for (const category of currentPostCategories) {
    if (!postCategoryOrder.includes(category.name) && Number(category.count || 0) === 0) {
      await deletePostCategory(category.name)
    }
  }
  await reorderPostCategories(postCategoryOrder)
}

async function main() {
  console.log('Seeding database...')

  const adminPassword = await bcrypt.hash('admin123', 10)
  const admin = await prisma.user.upsert({
    where: { username: 'admin' },
    update: {
      email: 'admin@triangle-portal.com',
      name: '系统管理员',
      password: adminPassword,
      role: 'admin',
      status: 'active',
      membershipLevel: 'free',
      avatar: '/avatars/defaults/avatar-02.png',
      gender: 'other',
    },
    create: {
      username: 'admin',
      email: 'admin@triangle-portal.com',
      password: adminPassword,
      name: '系统管理员',
      role: 'admin',
      status: 'active',
      membershipLevel: 'free',
      avatar: '/avatars/defaults/avatar-02.png',
      gender: 'other',
    },
  })
  console.log('Created admin user:', admin.username)

  // ==================== 等级配置数据 ====================
  const membershipLevels = [
    {
      key: 'free',
      name: '免费用户',
      description: '基础访问权限',
      sortOrder: 0,
      publicCertLimit: 1,
      dailyDownloadLimit: 3,
      blockedSoftwareTypes: '[]',
      rechargePrice: 0,
      rechargeBonusPercent: 0,
      color: '#6B7280',
      icon: 'star',
      isActive: true,
    },
    {
      key: 'sponsor',
      name: '赞助会员',
      description: '解锁更多下载和签名额度',
      sortOrder: 1,
      publicCertLimit: 5,
      dailyDownloadLimit: 20,
      blockedSoftwareTypes: '[]',
      rechargePrice: 9.9,
      rechargeBonusPercent: 10,
      color: '#3B82F6',
      icon: 'crown',
      isActive: true,
    },
    {
      key: 'lifetime',
      name: '终身会员',
      description: '一次购买，永久享受全部权益',
      sortOrder: 2,
      publicCertLimit: -1,
      dailyDownloadLimit: -1,
      blockedSoftwareTypes: '[]',
      rechargePrice: 99.0,
      rechargeBonusPercent: 20,
      color: '#8B5CF6',
      icon: 'gem',
      isActive: true,
    },
    {
      key: 'supreme',
      name: '至尊会员',
      description: '顶级权益，专属客服支持',
      sortOrder: 3,
      publicCertLimit: -1,
      dailyDownloadLimit: -1,
      blockedSoftwareTypes: '[]',
      rechargePrice: 299.0,
      rechargeBonusPercent: 50,
      color: '#F59E0B',
      icon: 'rocket',
      isActive: true,
    },
  ]

  for (const level of membershipLevels) {
    await prisma.membershipLevelConfig.upsert({
      where: { key: level.key },
      update: level,
      create: level,
    })
  }
  console.log('Created membership level configs')

  // ==================== 软件数据 ====================
  const apps = [
    // === 浏览器 ===
    {
      slug: 'chrome',
      name: 'Google Chrome',
      subtitle: '速度快、兼容性强的主流浏览器',
      category: '浏览器',
      icon: 'https://placehold.co/128x128/f59e0b/ffffff?text=CH',
      version: '134.0.6998.88',
      size: '112 MB',
      rating: 4.8,
      downloads: '10,000,000+',
      updatedAt: '2026-03-15',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/111827/ffffff?text=Chrome',
      displayMode: 'cover',
      gallery: [],
      tags: ['浏览器', 'Google', '网络'],
      verified: true,
      editorialScore: 95,
      pricing: '免费',
      summary: 'Google Chrome 是最常见的浏览器之一，适合拿来做日常上网、网页调试和账号同步。',
      highlights: ['页面加载速度快', '账号同步方便', '扩展生态成熟'],
      requirements: ['Windows 10 及以上', '至少 2GB 内存', '至少 500MB 可用空间'],
      featured: true,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://dl.google.com/chrome/install/standalone/chrome_installer.exe',
      downloadLinks: [
        { name: 'Windows 官方版', url: 'https://dl.google.com/chrome/install/standalone/chrome_installer.exe', platform: 'Windows' },
        { name: 'macOS 官方版', url: 'https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'firefox',
      name: 'Mozilla Firefox',
      subtitle: '注重隐私的开源浏览器',
      category: '浏览器',
      icon: 'https://placehold.co/128x128/ff7136/ffffff?text=FF',
      version: '135.0',
      size: '78 MB',
      rating: 4.6,
      downloads: '3,500,000+',
      updatedAt: '2026-03-12',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Linux', 'Android', 'iOS'],
      platforms: ['Windows', 'macOS', 'Linux', 'Android', 'iOS'],
      heroImage: 'https://placehold.co/1200x630/ff7136/ffffff?text=Firefox',
      displayMode: 'cover',
      gallery: [],
      tags: ['浏览器', '隐私', '开源'],
      verified: true,
      editorialScore: 89,
      pricing: '免费',
      summary: 'Firefox 以隐私保护为核心卖点，适合对浏览器追踪有顾虑的用户，同时保持良好的扩展生态。',
      highlights: ['隐私保护强', '内存占用低', '扩展生态丰富'],
      requirements: ['Windows 10 及以上', '至少 2GB 内存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.mozilla.org/firefox/download/',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.mozilla.org/firefox/download/thanks/', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://www.mozilla.org/firefox/download/mac/', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'edge',
      name: 'Microsoft Edge',
      subtitle: '基于 Chromium 的高效浏览器',
      category: '浏览器',
      icon: 'https://placehold.co/128x128/0078d4/ffffff?text=ED',
      version: '134.0.2968.0',
      size: '125 MB',
      rating: 4.5,
      downloads: '5,500,000+',
      updatedAt: '2026-03-10',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Linux', 'Android', 'iOS'],
      platforms: ['Windows', 'macOS', 'Linux', 'Android', 'iOS'],
      heroImage: 'https://placehold.co/1200x630/0078d4/ffffff?text=Edge',
      displayMode: 'cover',
      gallery: [],
      tags: ['浏览器', 'Microsoft', '网络'],
      verified: true,
      editorialScore: 88,
      pricing: '免费',
      summary: 'Edge 浏览器基于 Chromium 内核，拥有出色的性能表现和深度集成的 Microsoft 服务。',
      highlights: ['性能优秀', '集成了 Bing AI', '同步 Microsoft 账户'],
      requirements: ['Windows 10 及以上', '至少 4GB 内存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.microsoft.com/edge/download',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.microsoft.com/edge/download', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://www.microsoft.com/edge/download', platform: 'macOS' },
      ],
      affiliateLink: '',
    },

    // === 开发工具 ===
    {
      slug: 'vscode',
      name: 'Visual Studio Code',
      subtitle: '轻量但强大的代码编辑器',
      category: '开发工具',
      icon: 'https://placehold.co/128x128/2563eb/ffffff?text=VS',
      version: '1.96.0',
      size: '95 MB',
      rating: 4.9,
      downloads: '5,000,000+',
      updatedAt: '2026-03-20',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/1d4ed8/ffffff?text=VS+Code',
      displayMode: 'cover',
      gallery: [],
      tags: ['IDE', '代码编辑器', 'Microsoft'],
      verified: true,
      editorialScore: 97,
      pricing: '免费',
      summary: 'VS Code 适合绝大多数前端、后端和脚本开发场景，扩展丰富，启动也足够轻快。',
      highlights: ['扩展生态成熟', 'Git 集成完善', '调试能力完整'],
      requirements: ['Windows 10 及以上', '至少 1GB 内存'],
      featured: true,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://code.visualstudio.com/sha/download?build=stable&os=win32-x64',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://code.visualstudio.com/sha/download?build=stable&os=win32-x64', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://code.visualstudio.com/sha/download?build=stable&os=darwin', platform: 'macOS' },
        { name: 'Linux 版本', url: 'https://code.visualstudio.com/sha/download?build=stable&os=linux-x64', platform: 'Linux' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'git',
      name: 'Git',
      subtitle: '分布式版本控制系统',
      category: '开发工具',
      icon: 'https://placehold.co/128x128/f05033/ffffff?text=GT',
      version: '2.45.0',
      size: '48 MB',
      rating: 4.9,
      downloads: '8,000,000+',
      updatedAt: '2026-02-15',
      compatibility: ['Windows', 'macOS', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/f05033/ffffff?text=Git',
      displayMode: 'cover',
      gallery: [],
      tags: ['版本控制', '开发工具', '开源'],
      verified: true,
      editorialScore: 98,
      pricing: '免费',
      summary: 'Git 是现代软件开发必备的版本控制工具，支持分布式协作和高效的代码分支管理。',
      highlights: ['分支管理灵活', '性能优异', '社区资源丰富'],
      requirements: ['Windows 7 及以上', '至少 512MB 内存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://git-scm.com/download/win',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://git-scm.com/download/win', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://git-scm.com/download/mac', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'docker',
      name: 'Docker Desktop',
      subtitle: '容器化应用开发平台',
      category: '开发工具',
      icon: 'https://placehold.co/128x128/2496ed/ffffff?text=DC',
      version: '4.28.0',
      size: '450 MB',
      rating: 4.7,
      downloads: '1,200,000+',
      updatedAt: '2026-03-18',
      compatibility: ['Windows 10+', 'macOS 11+'],
      platforms: ['Windows', 'macOS'],
      heroImage: 'https://placehold.co/1200x630/2496ed/ffffff?text=Docker',
      displayMode: 'cover',
      gallery: [],
      tags: ['容器', 'DevOps', '开发工具'],
      verified: true,
      editorialScore: 94,
      pricing: '免费/付费',
      summary: 'Docker 让你可以打包、分发和运行任何应用在隔离的容器中，是现代云原生开发的基础设施。',
      highlights: ['环境一致性强', '资源占用合理', '生态完善'],
      requirements: ['Windows 10+ (WSL2)', '至少 4GB 内存', '至少 8GB 可用空间'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.docker.com/products/docker-desktop/',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://desktop.docker.com/mac/main/arm64/Docker.dmg', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'postman',
      name: 'Postman',
      subtitle: 'API 开发与测试协作平台',
      category: '开发工具',
      icon: 'https://placehold.co/128x128/ff6c37/ffffff?text=PM',
      version: '11.0.0',
      size: '180 MB',
      rating: 4.8,
      downloads: '900,000+',
      updatedAt: '2026-03-05',
      compatibility: ['Windows 10+', 'macOS 11+', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/ff6c37/ffffff?text=Postman',
      displayMode: 'cover',
      gallery: [],
      tags: ['API', '测试', '协作'],
      verified: true,
      editorialScore: 92,
      pricing: '免费/付费',
      summary: 'Postman 是 API 测试领域最流行的工具，支持请求构建、环境变量、自动化测试和团队协作。',
      highlights: ['界面友好', '功能全面', '团队协作方便'],
      requirements: ['Windows 10 及以上', '至少 4GB 内存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.postman.com/downloads/',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://dl.pstmn.io/download/latest/win64', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://dl.pstmn.io/download/latest/mac', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'intellij-idea',
      name: 'IntelliJ IDEA',
      subtitle: 'Java/Kotlin 开发首选 IDE',
      category: '开发工具',
      icon: 'https://placehold.co/128x128/000000/ffffff?text=IJ',
      version: '2024.2.0',
      size: '950 MB',
      rating: 4.8,
      downloads: '2,000,000+',
      updatedAt: '2026-03-01',
      compatibility: ['Windows 10+', 'macOS 11+', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/000000/ffffff?text=IntelliJ',
      displayMode: 'cover',
      gallery: [],
      tags: ['IDE', 'Java', 'Kotlin'],
      verified: true,
      editorialScore: 95,
      pricing: '免费/付费',
      summary: 'IntelliJ IDEA 是 JetBrains 出品的旗舰级 IDE，尤其在 Java 和 Kotlin 开发领域无可匹敌。',
      highlights: ['代码智能补全强', '重构工具完善', '插件生态丰富'],
      requirements: ['Windows 10 及以上', '至少 8GB 内存', '推荐 16GB'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.jetbrains.com/idea/download/',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.jetbrains.com/idea/download/', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://www.jetbrains.com/idea/download/', platform: 'macOS' },
      ],
      affiliateLink: '',
    },

    // === 效率工具 ===
    {
      slug: 'notion',
      name: 'Notion',
      subtitle: '文档、数据库与协作一体化工作区',
      category: '效率工具',
      icon: 'https://placehold.co/128x128/111827/ffffff?text=NO',
      version: '4.0.0',
      size: '68 MB',
      rating: 4.7,
      downloads: '3,000,000+',
      updatedAt: '2026-02-28',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Web', 'iOS', 'Android'],
      platforms: ['Windows', 'macOS', 'Web', 'iOS', 'Android'],
      heroImage: 'https://placehold.co/1200x630/111827/ffffff?text=Notion',
      displayMode: 'cover',
      gallery: [],
      tags: ['笔记', '协作', '知识管理'],
      verified: true,
      editorialScore: 91,
      pricing: '免费/付费',
      summary: 'Notion 适合做团队协作文档、项目看板和知识库，尤其适合需要多人协同的场景。',
      highlights: ['模板丰富', '数据库能力强', '团队协作方便'],
      requirements: ['Windows 10 及以上', '至少 2GB 内存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.notion.so/desktop',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.notion.so/desktop/windows', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://www.notion.so/desktop/mac', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'obsidian',
      name: 'Obsidian',
      subtitle: '本地优先的知识管理笔记工具',
      category: '效率工具',
      icon: 'https://placehold.co/128x128/7c3aed/ffffff?text=OB',
      version: '1.8.0',
      size: '115 MB',
      rating: 4.9,
      downloads: '1,500,000+',
      updatedAt: '2026-03-10',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/7c3aed/ffffff?text=Obsidian',
      displayMode: 'cover',
      gallery: [],
      tags: ['笔记', '知识管理', 'Markdown'],
      verified: true,
      editorialScore: 96,
      pricing: '免费/付费',
      summary: 'Obsidian 适合做个人知识库、研究笔记和长期写作，尤其适合偏本地优先的工作流。',
      highlights: ['本地存储', '双向链接', '插件生态强'],
      requirements: ['Windows 10 及以上', '至少 4GB 内存', '至少 300MB 可用空间'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://obsidian.md/download',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://obsidian.md/download?platform=windows', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://obsidian.md/download?platform=macos', platform: 'macOS' },
        { name: 'Linux 版本', url: 'https://obsidian.md/download?platform=linux', platform: 'Linux' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'typora',
      name: 'Typora',
      subtitle: '简洁优雅的 Markdown 编辑器',
      category: '效率工具',
      icon: 'https://placehold.co/128x128/569a49/ffffff?text=TY',
      version: '1.9.0',
      size: '58 MB',
      rating: 4.8,
      downloads: '1,800,000+',
      updatedAt: '2026-01-15',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/569a49/ffffff?text=Typora',
      displayMode: 'cover',
      gallery: [],
      tags: ['Markdown', '写作', '笔记'],
      verified: true,
      editorialScore: 94,
      pricing: '付费/免费测试版',
      summary: 'Typora 追求所见即所得的 Markdown 编辑体验，消除了编辑器和预览的分离感，让写作更加专注。',
      highlights: ['所见即所得', '主题美观', '导出格式丰富'],
      requirements: ['Windows 10 及以上', '至少 2GB 内存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://typora.io/downloads',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://typora.io/windows/release.html', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://typora.io/mac/dev_release.html', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'ticktick',
      name: 'TickTick',
      subtitle: '简洁高效的任务管理与日程规划',
      category: '效率工具',
      icon: 'https://placehold.co/128x128/fc6011/ffffff?text=TT',
      version: '4.5.0',
      size: '45 MB',
      rating: 4.6,
      downloads: '1,000,000+',
      updatedAt: '2026-02-20',
      compatibility: ['Windows 10+', 'macOS 11+', 'Android', 'iOS', 'Web'],
      platforms: ['Windows', 'macOS', 'Android', 'iOS', 'Web'],
      heroImage: 'https://placehold.co/1200x630/fc6011/ffffff?text=TickTick',
      displayMode: 'cover',
      gallery: [],
      tags: ['任务管理', '日程', '效率'],
      verified: true,
      editorialScore: 88,
      pricing: '免费/付费',
      summary: 'TickTick 集任务管理、日程提醒、番茄钟于一体，界面简洁，功能实用，是 GTD 方法的绝佳实践工具。',
      highlights: ['轻量简洁', '番茄钟集成', '多端同步'],
      requirements: ['Windows 10 及以上', '至少 100MB 可用空间'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.ticktick.com/downloads',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.ticktick.com/downloads', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://www.ticktick.com/downloads', platform: 'macOS' },
      ],
      affiliateLink: '',
    },

    // === 设计工具 ===
    {
      slug: 'figma',
      name: 'Figma',
      subtitle: '团队协作型界面设计工具',
      category: '设计工具',
      icon: 'https://placehold.co/128x128/ec4899/ffffff?text=FI',
      version: '2026.001',
      size: '120 MB',
      rating: 4.8,
      downloads: '2,000,000+',
      updatedAt: '2026-03-01',
      compatibility: ['Web', 'Windows 10+', 'macOS 11+'],
      platforms: ['Web', 'Windows', 'macOS'],
      heroImage: 'https://placehold.co/1200x630/ec4899/ffffff?text=Figma',
      displayMode: 'cover',
      gallery: [],
      tags: ['UI设计', '原型', '协作'],
      verified: true,
      editorialScore: 93,
      pricing: '免费/付费',
      summary: 'Figma 适合做 UI 设计、交互原型和多人协作评审，是设计团队最常见的工具之一。',
      highlights: ['实时协作', '跨平台', '组件体系成熟'],
      requirements: ['Windows 10 及以上', '至少 4GB 内存'],
      featured: true,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.figma.com/download/desktop/win',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.figma.com/download/desktop/win', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://www.figma.com/download/desktop/mac', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'photoshop',
      name: 'Adobe Photoshop',
      subtitle: '专业级图像编辑与设计软件',
      category: '设计工具',
      icon: 'https://placehold.co/128x128/31a8ff/ffffff?text=PS',
      version: '2026.1.0',
      size: '4.5 GB',
      rating: 4.7,
      downloads: '5,000,000+',
      updatedAt: '2026-03-01',
      compatibility: ['Windows 10+', 'macOS 12+'],
      platforms: ['Windows', 'macOS'],
      heroImage: 'https://placehold.co/1200x630/31a8ff/ffffff?text=Photoshop',
      displayMode: 'cover',
      gallery: [],
      tags: ['图像处理', '设计', '创意'],
      verified: true,
      editorialScore: 96,
      pricing: '付费订阅',
      summary: 'Photoshop 是图像编辑的行业标准，从照片修图到数字绘画，从 UI 设计到 3D 编辑，功能无所不包。',
      highlights: ['功能最全面', '插件生态成熟', '行业标准'],
      requirements: ['Windows 10 及以上', '至少 16GB 内存', '至少 8GB 可用空间'],
      featured: true,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.adobe.com/products/photoshop.html',
      downloadLinks: [
        { name: '官网下载', url: 'https://www.adobe.com/products/photoshop.html', platform: 'Windows' },
        { name: '官网下载', url: 'https://www.adobe.com/products/photoshop.html', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'blender',
      name: 'Blender',
      subtitle: '开源全能 3D 创作套件',
      category: '设计工具',
      icon: 'https://placehold.co/128x128/ea7600/ffffff?text=BL',
      version: '4.2.0',
      size: '300 MB',
      rating: 4.8,
      downloads: '800,000+',
      updatedAt: '2026-02-20',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/ea7600/ffffff?text=Blender',
      displayMode: 'cover',
      gallery: [],
      tags: ['3D建模', '动画', '开源'],
      verified: true,
      editorialScore: 95,
      pricing: '免费',
      summary: 'Blender 是开源 3D 创作神器，集建模、雕刻、动画、渲染、视频编辑于一身，完全免费。',
      highlights: ['功能完整', '社区活跃', '完全免费'],
      requirements: ['Windows 10 及以上', '至少 8GB 内存', '至少 4GB 显存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.blender.org/download/',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.blender.org/download/', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://www.blender.org/download/', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'eagle',
      name: 'Eagle',
      subtitle: '设计师必备的图片素材管理工具',
      category: '设计工具',
      icon: 'https://placehold.co/128x128/5727ff/ffffff?text=EG',
      version: '9.5.0',
      size: '180 MB',
      rating: 4.8,
      downloads: '500,000+',
      updatedAt: '2026-03-15',
      compatibility: ['Windows 10+', 'macOS 11+'],
      platforms: ['Windows', 'macOS'],
      heroImage: 'https://placehold.co/1200x630/5727ff/ffffff?text=Eagle',
      displayMode: 'cover',
      gallery: [],
      tags: ['素材管理', '设计工具', '效率'],
      verified: true,
      editorialScore: 93,
      pricing: '付费',
      summary: 'Eagle 专为设计师打造，支持从网页、截图、Pinterest 等多渠道收集灵感，强大的分类和标签功能让素材管理井井有条。',
      highlights: ['收集便捷', '分类灵活', '预览高效'],
      requirements: ['Windows 10 及以上', '至少 4GB 内存', '至少 1GB 可用空间'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://eagle.cool/download',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://eagle.cool/download', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://eagle.cool/download', platform: 'macOS' },
      ],
      affiliateLink: '',
    },

    // === 多媒体 ===
    {
      slug: 'obs',
      name: 'OBS Studio',
      subtitle: '免费开源的直播与录屏软件',
      category: '多媒体',
      icon: 'https://placehold.co/128x128/302934/ffffff?text=OB',
      version: '30.2.0',
      size: '120 MB',
      rating: 4.9,
      downloads: '2,500,000+',
      updatedAt: '2026-03-08',
      compatibility: ['Windows 10+', 'macOS 11+', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/302934/ffffff?text=OBS+Studio',
      displayMode: 'cover',
      gallery: [],
      tags: ['直播', '录屏', '开源'],
      verified: true,
      editorialScore: 96,
      pricing: '免费',
      summary: 'OBS Studio 是游戏直播、在线课程录制和视频教程制作的首选工具，支持多场景切换和实时滤镜。',
      highlights: ['功能专业', '性能优秀', '完全免费'],
      requirements: ['Windows 10 及以上', '至少 4GB 内存', '支持 DirectX 10.1 的显卡'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://obsproject.com/downloads',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://obsproject.com/downloads', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://obsproject.com/downloads', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'shotcut',
      name: 'Shotcut',
      subtitle: '跨平台开源视频编辑器',
      category: '多媒体',
      icon: 'https://placehold.co/128x128/111111/ffffff?text=SC',
      version: '24.08.0',
      size: '150 MB',
      rating: 4.5,
      downloads: '600,000+',
      updatedAt: '2026-02-25',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/111111/ffffff?text=Shotcut',
      displayMode: 'cover',
      gallery: [],
      tags: ['视频编辑', '开源', '轻量'],
      verified: true,
      editorialScore: 85,
      pricing: '免费',
      summary: 'Shotcut 是一款免费开源的视频编辑器，界面简洁易上手，支持数百种音视频格式，无需转换。',
      highlights: ['格式支持广', '界面简洁', '免费无广告'],
      requirements: ['Windows 10 及以上', '至少 2GB 内存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.shotcut.org/download/',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.shotcut.org/download/', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://www.shotcut.org/download/', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'handbrake',
      name: 'HandBrake',
      subtitle: '免费开源的视频格式转换工具',
      category: '多媒体',
      icon: 'https://placehold.co/128x128/14b8a6/ffffff?text=HB',
      version: '1.8.0',
      size: '40 MB',
      rating: 4.7,
      downloads: '1,200,000+',
      updatedAt: '2026-01-28',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Linux'],
      platforms: ['Windows', 'macOS', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/14b8a6/ffffff?text=HandBrake',
      displayMode: 'cover',
      gallery: [],
      tags: ['视频转换', '编码', '开源'],
      verified: true,
      editorialScore: 90,
      pricing: '免费',
      summary: 'HandBrake 是免费开源的视频转码工具，支持几乎所有主流视频格式，输出质量高且文件体积优化好。',
      highlights: ['格式支持全', '压缩效率高', '完全免费'],
      requirements: ['Windows 10 及以上', '至少 4GB 内存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://handbrake.fr/downloads.php',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://handbrake.fr/downloads.php', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://handbrake.fr/downloads.php', platform: 'macOS' },
      ],
      affiliateLink: '',
    },

    // === 系统工具 ===
    {
      slug: '7zip',
      name: '7-Zip',
      subtitle: '高效开源的文件压缩工具',
      category: '系统工具',
      icon: 'https://placehold.co/128x128/000000/ffffff?text=7Z',
      version: '24.07',
      size: '1.5 MB',
      rating: 4.9,
      downloads: '15,000,000+',
      updatedAt: '2026-02-10',
      compatibility: ['Windows XP+', 'Linux (通过命令行)'],
      platforms: ['Windows', 'Linux'],
      heroImage: 'https://placehold.co/1200x630/000000/ffffff?text=7-Zip',
      displayMode: 'cover',
      gallery: [],
      tags: ['压缩', '解压', '开源'],
      verified: true,
      editorialScore: 97,
      pricing: '免费',
      summary: '7-Zip 是 Windows 上最受欢迎的压缩工具，支持 7z、ZIP、RAR 等多种格式，压缩率极高。',
      highlights: ['压缩率高', '体积小巧', '完全免费'],
      requirements: ['Windows XP 及以上'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.7-zip.org/download.html',
      downloadLinks: [
        { name: 'Windows 版本 (64位)', url: 'https://www.7-zip.org/a/7z2407-x64.exe', platform: 'Windows' },
        { name: 'Windows 版本 (32位)', url: 'https://www.7-zip.org/a/7z2407.exe', platform: 'Windows' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'everything',
      name: 'Everything',
      subtitle: 'Windows 文件快速搜索工具',
      category: '系统工具',
      icon: 'https://placehold.co/128x128/1f8dd6/ffffff?text=EV',
      version: '1.4.1.1020',
      size: '3 MB',
      rating: 4.9,
      downloads: '3,000,000+',
      updatedAt: '2026-01-20',
      compatibility: ['Windows XP+'],
      platforms: ['Windows'],
      heroImage: 'https://placehold.co/1200x630/1f8dd6/ffffff?text=Everything',
      displayMode: 'cover',
      gallery: [],
      tags: ['文件搜索', '效率', '轻量'],
      verified: true,
      editorialScore: 96,
      pricing: '免费',
      summary: 'Everything 是 Windows 上最快的文件搜索工具，输入即显示结果，再大的硬盘也能秒搜。',
      highlights: ['搜索速度极快', '占用资源极少', '界面简洁'],
      requirements: ['Windows XP 及以上'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.voidtools.com/downloads/',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.voidtools.com/downloads/', platform: 'Windows' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'listary',
      name: 'Listary',
      subtitle: '让你的 Windows 搜索无处不在',
      category: '系统工具',
      icon: 'https://placehold.co/128x128/ff6b35/ffffff?text=LS',
      version: '6.3.0',
      size: '5 MB',
      rating: 4.7,
      downloads: '800,000+',
      updatedAt: '2026-02-05',
      compatibility: ['Windows 10+'],
      platforms: ['Windows'],
      heroImage: 'https://placehold.co/1200x630/ff6b35/ffffff?text=Listary',
      displayMode: 'cover',
      gallery: [],
      tags: ['搜索', '效率', '快捷操作'],
      verified: true,
      editorialScore: 91,
      pricing: '免费/付费',
      summary: 'Listary 让你在任何界面按两次 Ctrl 就能调出搜索框，快速找到文件、启动程序、甚至进行网络搜索。',
      highlights: ['全局快捷键', '动作命令', '快速访问历史'],
      requirements: ['Windows 10 及以上'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.listary.com/download',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.listary.com/download', platform: 'Windows' },
      ],
      affiliateLink: '',
    },

    // === 办公协作 ===
    {
      slug: 'slack',
      name: 'Slack',
      subtitle: '团队协作与即时通讯平台',
      category: '办公协作',
      icon: 'https://placehold.co/128x128/4a154b/ffffff?text=SL',
      version: '4.40.0',
      size: '180 MB',
      rating: 4.5,
      downloads: '2,000,000+',
      updatedAt: '2026-03-15',
      compatibility: ['Windows 10+', 'macOS 11+', 'Linux', 'iOS', 'Android', 'Web'],
      platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android', 'Web'],
      heroImage: 'https://placehold.co/1200x630/4a154b/ffffff?text=Slack',
      displayMode: 'cover',
      gallery: [],
      tags: ['协作', '即时通讯', '远程办公'],
      verified: true,
      editorialScore: 89,
      pricing: '免费/付费',
      summary: 'Slack 是企业团队协作的首选工具，频道分类、消息搜索、应用集成让团队沟通井井有条。',
      highlights: ['频道分类清晰', '搜索功能强大', '集成丰富'],
      requirements: ['Windows 10 及以上', '至少 4GB 内存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://slack.com/downloads/windows',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://slack.com/downloads/windows', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://slack.com/downloads/mac', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
    {
      slug: 'wps-office',
      name: 'WPS Office',
      subtitle: '国产办公软件套装',
      category: '办公协作',
      icon: 'https://placehold.co/128x128/ff6a00/ffffff?text=WP',
      version: '12.8.0',
      size: '220 MB',
      rating: 4.4,
      downloads: '8,000,000+',
      updatedAt: '2026-03-10',
      compatibility: ['Windows 10+', 'macOS 10.15+', 'Linux', 'iOS', 'Android'],
      platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android'],
      heroImage: 'https://placehold.co/1200x630/ff6a00/ffffff?text=WPS',
      displayMode: 'cover',
      gallery: [],
      tags: ['办公', '文档', '国产'],
      verified: true,
      editorialScore: 86,
      pricing: '免费',
      summary: 'WPS Office 是国产办公软件套装，兼容 Microsoft Office 格式，体积小巧适合日常办公。',
      highlights: ['格式兼容好', '体积小巧', '模板丰富'],
      requirements: ['Windows 10 及以上', '至少 2GB 内存'],
      featured: false,
      status: 'published',
      accessLevel: 'free',
      isDownloadable: true,
      downloadUrl: 'https://www.wps.cn/',
      downloadLinks: [
        { name: 'Windows 版本', url: 'https://www.wps.cn/', platform: 'Windows' },
        { name: 'macOS 版本', url: 'https://www.wps.cn/', platform: 'macOS' },
      ],
      affiliateLink: '',
    },
  ]

  for (const appData of apps) {
    const app = await prisma.app.upsert({
      where: { slug: appData.slug },
      update: {
        ...appData,
        authorId: admin.id,
      },
      create: {
        ...appData,
        authorId: admin.id,
      },
    })
    console.log('Created app:', app.name)
  }

  // ==================== 文章数据 ====================
  const posts = [
    {
      slug: 'best-free-software-2026',
      title: '2026 年值得收藏的免费软件清单',
      excerpt: '覆盖浏览器、开发、设计、效率工具四大类，适合新机器装机与长期使用。',
      content: `<h2>推荐理由</h2><p>这份清单以稳定性、易用性和中文用户上手成本为标准，整理了当前仍然值得长期使用的免费软件。</p><p>如果你正在给新电脑装机，这一篇可以当作起点。</p><h2>浏览器推荐</h2><p>Chrome 和 Firefox 依然是绝对主力。Chrome 适合需要深度浏览器扩展的用户，Firefox 则更适合注重隐私保护的场景。</p><h2>开发工具推荐</h2><p>VS Code 依然是前端、后端开发的首选编辑器，配合 Git 和 Docker，整个开发工作流都可以免费搭建。</p><h2>效率工具推荐</h2><p>Obsidian 和 Typora 是文字工作者的绝佳搭档，前者适合构建个人知识网络，后者适合纯粹的 Markdown 写作。</p>`,
      category: SOFTWARE_RECOMMEND_CATEGORY,
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/0f172a/ffffff?text=Best+Free+Software',
      icon: 'https://placehold.co/256x256/0f172a/ffffff?text=清单',
      displayMode: 'cover',
      relatedAppSlug: 'chrome',
      featured: true,
      readingTime: '8 分钟',
      dateLabel: '2026-03-20',
      publishedAt: '2026-03-20',
      status: 'published',
    },
    {
      slug: 'vscode-extensions-guide',
      title: 'VS Code 必装扩展推荐',
      excerpt: '从格式化、Git、调试到 AI 辅助，整理出一套适合中文开发者的扩展组合。',
      content: `<h2>扩展建议</h2><p>不建议一开始装太多扩展，先把格式化、Git、语言支持和调试工具配齐，再按项目类型补充。</p><h2>必备扩展</h2><ul><li>Prettier - 代码格式化</li><li>ESLint - 代码检查</li><li>GitLens - Git 可视化</li><li>Auto Rename Tag - 自动补全标签</li><li>Error Lens - 错误高亮</li></ul><h2>语言支持</h2><p>根据你的技术栈选择对应的语言扩展，TypeScript、Python、Go、Rust 等都有官方维护的高质量扩展。</p>`,
      category: '开发工具',
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/1d4ed8/ffffff?text=VSCode+Extensions',
      icon: 'https://placehold.co/256x256/1d4ed8/ffffff?text=VS',
      displayMode: 'cover',
      relatedAppSlug: 'vscode',
      featured: false,
      readingTime: '6 分钟',
      dateLabel: '2026-03-15',
      publishedAt: '2026-03-15',
      status: 'published',
    },
    {
      slug: 'knowledge-management-tools',
      title: 'Notion 与 Obsidian 该怎么选',
      excerpt: '不是简单二选一，而是看你的工作流到底更偏协作数据库，还是更偏本地知识积累。',
      content: `<h2>结论先行</h2><p>如果你更看重团队协作与结构化管理，Notion 更合适；如果你更看重本地优先、知识网络和长期写作，Obsidian 更适合。</p><h2>Notion 的优势</h2><p>Notion 的数据库视图、多人实时协作和模板系统非常强大，特别适合产品经理、项目管理和团队知识库场景。</p><h2>Obsidian 的优势</h2><p>Obsidian 的本地优先策略、双向链接和图谱视图让你能够真正构建个人知识网络。Markdown 格式也保证了数据的长久可移植性。</p><h2>我的建议</h2><p>可以两者结合使用：Notion 作为团队协作入口，Obsidian 作为个人深度思考和写作的工具。</p>`,
      category: '效率工具',
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/16a34a/ffffff?text=Notion+vs+Obsidian',
      icon: 'https://placehold.co/256x256/16a34a/ffffff?text=PK',
      displayMode: 'cover',
      relatedAppSlug: 'obsidian',
      featured: true,
      readingTime: '12 分钟',
      dateLabel: '2026-03-10',
      publishedAt: '2026-03-10',
      status: 'published',
    },
    {
      slug: 'figma-for-beginners',
      title: 'Figma 入门指南：从零开始搭建第一个界面',
      excerpt: '从画板、组件、自动布局到标注交付，带你完成完整的第一张页面设计。',
      content: `<h2>入门建议</h2><p>刚开始使用 Figma 时，优先熟悉 Frame、Auto Layout、组件和样式，先把基础操作打牢，再去追求复杂效果。</p><h2>第一步：创建画板</h2><p>使用快捷键 F 可以快速创建画板，Figma 默认提供了移动端、Web 端和桌面端的预设尺寸。</p><h2>第二步：使用组件</h2><p>Figma 的组件系统是其核心功能之一，学会创建和使用组件，可以大大提高设计效率。</p><h2>第三步：自动布局</h2><p>Auto Layout 让你的设计能够自适应内容变化，是做响应式设计的神器。</p>`,
      category: '设计工具',
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/f97316/ffffff?text=Figma+Guide',
      icon: 'https://placehold.co/256x256/f97316/ffffff?text=FG',
      displayMode: 'cover',
      relatedAppSlug: 'figma',
      featured: false,
      readingTime: '10 分钟',
      dateLabel: '2026-03-05',
      publishedAt: '2026-03-05',
      status: 'published',
    },
    {
      slug: 'chrome-tips-tricks',
      title: 'Chrome 进阶技巧：这几项设置先改掉',
      excerpt: '从标签页管理到安全设置，几分钟把浏览器调到更顺手的状态。',
      content: `<h2>推荐设置</h2><p>建议优先开启密码安全检查、标签分组和同步策略，再根据自己的使用习惯调整启动页与搜索引擎。</p><h2>标签页管理</h2><p>Chrome 的标签页太多会严重影响内存占用，学会使用标签页分组和休眠功能可以显著提升浏览器性能。</p><h2>隐私与安全</h2><p>定期检查密码安全、关闭不需要的通知权限、使用隐私浏览模式访问敏感网站。</p>`,
      category: '软件教程',
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/334155/ffffff?text=Chrome+Tips',
      icon: 'https://placehold.co/256x256/334155/ffffff?text=CH',
      displayMode: 'cover',
      relatedAppSlug: 'chrome',
      featured: false,
      readingTime: '5 分钟',
      dateLabel: '2026-02-28',
      publishedAt: '2026-02-28',
      status: 'published',
    },
    // 新增文章
    {
      slug: 'obsidian-plugin-guide',
      title: 'Obsidian 插件推荐：打造你的第二大脑',
      excerpt: '从必装插件到进阶配置，手把手教你用 Obsidian 构建个人知识管理系统。',
      content: `<h2>为什么选择 Obsidian</h2><p>Obsidian 的核心优势在于本地存储和双向链接，这意味着你的笔记完全属于你自己，不会被任何平台绑架。</p><h2>必装核心插件</h2><ul><li>Kanban - 看板式任务管理</li><li>Templater - 模板系统增强</li><li>Dataview - 动态数据查询</li><li>Admonition - 信息提示块</li><li>Homepage - 自定义启动页</li></ul><h2>进阶配置建议</h2><p>建议配合 Git 进行笔记同步，配合 Daily Notes 插件建立每日写作习惯。</p>`,
      category: '效率工具',
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/7c3aed/ffffff?text=Obsidian+Plugins',
      icon: 'https://placehold.co/256x256/7c3aed/ffffff?text=OB',
      displayMode: 'cover',
      relatedAppSlug: 'obsidian',
      featured: true,
      readingTime: '15 分钟',
      dateLabel: '2026-03-18',
      publishedAt: '2026-03-18',
      status: 'published',
    },
    {
      slug: 'docker-getting-started',
      title: 'Docker 入门教程：让开发环境一键就绪',
      excerpt: '从安装到跑通第一个容器，手把手教你用 Docker 解决「在我机器上能跑」的问题。',
      content: `<h2>Docker 是什么</h2><p>Docker 是一个容器化平台，让你可以把应用和它的依赖打包成一个轻量级的容器，确保在任何环境下都能一致运行。</p><h2>核心概念</h2><ul><li><strong>镜像（Image）</strong>：应用的只读模板</li><li><strong>容器（Container）</strong>：镜像的运行实例</li><li><strong>仓库（Repository）</strong>：存储和分发镜像的地方</li></ul><h2>第一个容器</h2><p>让我们从运行一个简单的 Nginx 容器开始，体验 Docker 的魅力。</p>`,
      category: '开发工具',
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/2496ed/ffffff?text=Docker+Guide',
      icon: 'https://placehold.co/256x256/2496ed/ffffff?text=DC',
      displayMode: 'cover',
      relatedAppSlug: 'docker',
      featured: false,
      readingTime: '12 分钟',
      dateLabel: '2026-03-12',
      publishedAt: '2026-03-12',
      status: 'published',
    },
    {
      slug: 'blender-3d-modeling-guide',
      title: 'Blender 入门：用开源工具做 3D 设计',
      excerpt: '从界面认知到第一个建模作品，适合零基础新手的 Blender 入门指南。',
      content: `<h2>为什么选择 Blender</h2><p>Blender 是一款完全免费的开源 3D 创作套件，功能强大到可以与付费软件一较高下。从简单的产品展示图到复杂的动画短片，Blender 都能胜任。</p><h2>界面布局</h2><p>Blender 的界面设计非常独特，默认布局包含 3D 视口、时间线、属性面板等核心区域。建议新手先熟悉这套布局，再根据自己的工作流进行调整。</p><h2>建模基础</h2><p>从添加基础几何体开始，逐步学习编辑模式下的顶点、边、面操作，这是所有 3D 建模的起点。</p>`,
      category: '设计工具',
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/ea7600/ffffff?text=Blender+Guide',
      icon: 'https://placehold.co/256x256/ea7600/ffffff?text=BL',
      displayMode: 'cover',
      relatedAppSlug: 'blender',
      featured: false,
      readingTime: '18 分钟',
      dateLabel: '2026-03-08',
      publishedAt: '2026-03-08',
      status: 'published',
    },
    {
      slug: 'obs-live-streaming-guide',
      title: 'OBS 直播设置全攻略：从入门到精通',
      excerpt: '游戏直播、在线课堂、知识分享，手把手教你用 OBS Studio 打造专业级直播。',
      content: `<h2>OBS 能做什么</h2><p>OBS Studio 是游戏直播、在线课程录制和视频教程制作的首选工具。它支持多场景切换、画面滤镜、音频混合等专业功能，而且完全免费。</p><h2>基础设置</h2><p>首次使用需要配置编码器和输出设置。对于大多数用户，推荐使用 NVENC 或 H.264 编码，码率建议设置在 4000-8000 kbps 之间。</p><h2>场景配置</h2><p>建议设置多个场景：开场场景、游戏场景、聊天场景，方便在直播中快速切换。</p>`,
      category: '多媒体',
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/302934/ffffff?text=OBS+Streaming',
      icon: 'https://placehold.co/256x256/302934/ffffff?text=OB',
      displayMode: 'cover',
      relatedAppSlug: 'obs',
      featured: false,
      readingTime: '14 分钟',
      dateLabel: '2026-03-02',
      publishedAt: '2026-03-02',
      status: 'published',
    },
    {
      slug: 'windows-efficiency-tools',
      title: 'Windows 效率神器：这些工具让你快人一步',
      excerpt: '从文件搜索到剪贴板管理，推荐 10 款让 Windows 更好用的效率工具。',
      content: `<h2>文件搜索：Everything</h2><p>Windows 自带的搜索功能太慢？Everything 可以让你在输入的瞬间就看到搜索结果，速度快到令人惊叹。</p><h2>剪贴板管理：Ditto</h2><p>Ditto 是一款开源的剪贴板增强工具，支持历史记录、格式转换和多设备同步。</p><h2>快速启动：Listary</h2><p>在任何界面双击 Ctrl 就能调出搜索框，快速找到文件或启动程序。</p><h2>窗口管理：PowerToys</h2><p>微软官方出品的 Windows 工具箱，包含窗口布局、批量重命名、键盘快捷管理器等实用功能。</p>`,
      category: '系统工具',
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/0078d4/ffffff?text=Windows+Tools',
      icon: 'https://placehold.co/256x256/0078d4/ffffff?text=WIN',
      displayMode: 'cover',
      relatedAppSlug: 'everything',
      featured: false,
      readingTime: '10 分钟',
      dateLabel: '2026-02-25',
      publishedAt: '2026-02-25',
      status: 'published',
    },
    {
      slug: 'figma-vs-sketch',
      title: 'Figma vs Sketch：UI 设计工具如何选',
      excerpt: '两大主流设计工具全方位对比，帮你找到最适合自己和团队的那一款。',
      content: `<h2>平台支持</h2><p>Sketch 只支持 macOS，这是它最大的限制。Figma 则是基于浏览器的应用，Windows、macOS、Linux 都能完美运行。</p><h2>协作能力</h2><p>Figma 的实时协作功能是其最大亮点，多人可以同时编辑同一个文件。而 Sketch 需要借助 Abstract 等第三方工具才能实现类似功能。</p><h2>插件生态</h2><p>两者都有丰富的插件生态，但 Figma 的插件开发门槛更低，社区更加活跃。</p><h2>价格</h2><p>Sketch 按年订阅，Figma 提供免费版本。对于小型团队和个人用户，Figma 的免费版已经足够使用。</p>`,
      category: '设计工具',
      author: 'Triangle 编辑部',
      coverImage: 'https://placehold.co/1200x630/ec4899/ffffff?text=Figma+vs+Sketch',
      icon: 'https://placehold.co/256x256/ec4899/ffffff?text=VS',
      displayMode: 'cover',
      relatedAppSlug: 'figma',
      featured: false,
      readingTime: '8 分钟',
      dateLabel: '2026-02-20',
      publishedAt: '2026-02-20',
      status: 'published',
    },
  ]

  for (const postData of posts) {
    const post = await prisma.post.upsert({
      where: { slug: postData.slug },
      update: {
        ...postData,
        authorId: admin.id,
      },
      create: {
        ...postData,
        authorId: admin.id,
      },
    })
    console.log('Created post:', post.title)
  }

  // ==================== 专题数据 ====================
  const topic = await prisma.topic.upsert({
    where: { slug: 'productivity-workspace' },
    update: {
      title: '效率工作台',
      description: '整理高频效率工具、笔记工具与协作工具的实用内容。',
      coverImage: 'https://placehold.co/1200x630/0f766e/ffffff?text=Productivity',
      status: 'published',
    },
    create: {
      slug: 'productivity-workspace',
      title: '效率工作台',
      description: '整理高频效率工具、笔记工具与协作工具的实用内容。',
      coverImage: 'https://placehold.co/1200x630/0f766e/ffffff?text=Productivity',
      status: 'published',
    },
  })

  await prisma.topicApp.upsert({
    where: { topicId_appSlug: { topicId: topic.id, appSlug: 'notion' } },
    update: {},
    create: { topicId: topic.id, appSlug: 'notion' },
  })

  await prisma.topicApp.upsert({
    where: { topicId_appSlug: { topicId: topic.id, appSlug: 'obsidian' } },
    update: {},
    create: { topicId: topic.id, appSlug: 'obsidian' },
  })

  await prisma.topicApp.upsert({
    where: { topicId_appSlug: { topicId: topic.id, appSlug: 'typora' } },
    update: {},
    create: { topicId: topic.id, appSlug: 'typora' },
  })

  await prisma.topicPost.upsert({
    where: { topicId_postSlug: { topicId: topic.id, postSlug: 'knowledge-management-tools' } },
    update: {},
    create: { topicId: topic.id, postSlug: 'knowledge-management-tools' },
  })

  await prisma.topicPost.upsert({
    where: { topicId_postSlug: { topicId: topic.id, postSlug: 'obsidian-plugin-guide' } },
    update: {},
    create: { topicId: topic.id, postSlug: 'obsidian-plugin-guide' },
  })
  console.log('Created topic:', topic.title)

  // ==================== 需求墙数据 ====================
  const softwareRequests = [
    {
      id: 1,
      title: '希望整理一份适合新手的视频剪辑工具推荐',
      description: '最好覆盖免费方案、上手难度和适合自媒体场景的建议。',
      authorName: '社区用户',
      authorEmail: 'reader@example.com',
      status: 'done',
      adminReply: '已为你整理了 OBS Studio 和 Shotcut 两款免费工具的入门指南，可以前往文章区查看详细教程。',
      repliedAt: new Date('2026-03-10'),
    },
    {
      id: 2,
      title: '有没有适合程序员的设计工具推荐',
      description: '需要做一些简单的 UI 原型和流程图，希望工具不要太复杂，上手快一点。',
      authorName: '开发者小王',
      authorEmail: 'dev@example.com',
      status: 'done',
      adminReply: '推荐 Figma，免费版足够个人使用，界面直观且在线协作功能强大。',
      repliedAt: new Date('2026-03-12'),
    },
    {
      id: 3,
      title: 'Mac 上有什么好用的 Markdown 编辑器',
      description: '日常写笔记、写博客用，不希望太贵，最好有实时预览功能。',
      authorName: 'Mac 用户',
      authorEmail: 'mac@example.com',
      status: 'pending',
      adminReply: null,
      repliedAt: null,
    },
    {
      id: 4,
      title: '推荐一个适合 Windows 的效率启动工具',
      description: '类似 macOS 上 Alfred 那样的快速启动器，能搜索文件和应用就行。',
      authorName: '效率控',
      authorEmail: 'efficiency@example.com',
      status: 'done',
      adminReply: '推荐 Listary，按两下 Ctrl 就能调出搜索框，功能强大且免费版足够日常使用。',
      repliedAt: new Date('2026-03-15'),
    },
    {
      id: 5,
      title: '有什么免费好用的录屏软件推荐',
      description: '主要用于录制在线课程和软件教程，需要能录制系统声音和麦克风。',
      authorName: '讲师李老师',
      authorEmail: 'teacher@example.com',
      status: 'pending',
      adminReply: null,
      repliedAt: null,
    },
    {
      id: 6,
      title: '想找一款适合团队用的文档协作工具',
      description: '团队大概 5-6 个人，需要实时协作编辑、评论和版本历史功能。',
      authorName: '创业团队',
      authorEmail: 'startup@example.com',
      status: 'processing',
      adminReply: null,
      repliedAt: null,
    },
  ]

  for (const req of softwareRequests) {
    await prisma.softwareRequest.upsert({
      where: { id: req.id },
      update: {
        title: req.title,
        description: req.description,
        authorName: req.authorName,
        authorEmail: req.authorEmail,
        status: req.status,
        adminReply: req.adminReply,
        repliedAt: req.repliedAt,
      },
      create: req,
    })
  }
  console.log('Created software requests')

  // ==================== 热搜数据 ====================
  const hotSearches = [
    { keyword: 'chrome', type: 'app', count: 128 },
    { keyword: 'vscode', type: 'app', count: 105 },
    { keyword: 'notion', type: 'app', count: 98 },
    { keyword: 'figma', type: 'app', count: 87 },
    { keyword: '设计工具', type: 'all', count: 86 },
    { keyword: '效率工具', type: 'all', count: 75 },
    { keyword: 'obsidian', type: 'app', count: 65 },
    { keyword: '浏览器', type: 'all', count: 58 },
    { keyword: '开发工具', type: 'all', count: 52 },
    { keyword: '笔记', type: 'all', count: 48 },
    { keyword: 'Figma', type: 'app', count: 45 },
    { keyword: 'Blender', type: 'app', count: 42 },
    { keyword: 'Docker', type: 'app', count: 38 },
    { keyword: 'Photoshop', type: 'app', count: 35 },
    { keyword: 'Markdown', type: 'all', count: 32 },
  ]

  for (const search of hotSearches) {
    await prisma.hotSearch.upsert({
      where: { keyword: search.keyword },
      update: {
        type: search.type,
        count: search.count,
      },
      create: search,
    })
  }
  console.log('Created hot searches')

  // ==================== 公告数据 ====================
  const announcements = [
    {
      key: 'welcome',
      title: '欢迎使用 Triangle 软件分享平台',
      content: '这里是软件发现、分享与交流的地方。我们收录了各类优质工具，欢迎提出需求或分享你的使用心得。',
      kind: 'system',
      pinned: true,
    },
    {
      key: 'new-features',
      title: '新增软件签名功能',
      content: 'iOS 用户现在可以使用我们的签名服务来安装应用，详情请访问签名页面。',
      kind: 'notice',
      pinned: false,
    },
    {
      key: 'guidelines',
      title: '社区公约提醒',
      content: '请大家在需求墙发帖时，描述清楚软件用途、平台需求和预算范围，这样更容易得到有用的回复。',
      kind: 'notice',
      pinned: false,
    },
  ]

  for (const ann of announcements) {
    await prisma.notificationTemplate.upsert({
      where: { key: ann.key },
      update: {
        title: ann.title,
        content: ann.content,
        enabled: true,
      },
      create: {
        key: ann.key,
        title: ann.title,
        content: ann.content,
        enabled: true,
      },
    })
  }
  console.log('Created announcements')

  // ==================== 同步分类 ====================
  await syncCategoryTables(
    ['浏览器', '开发工具', '效率工具', '设计工具', '多媒体', '系统工具', '办公协作'],
    [SOFTWARE_RECOMMEND_CATEGORY, '开发工具', '效率工具', '设计工具', '软件教程', '多媒体', '系统工具'],
  )

  console.log('Seeding completed!')
}

main()
  .catch((error) => {
    console.error('Seed error:', error)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
