
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `HotSearch` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model HotSearch
 * 
 */
export type HotSearchModel = runtime.Types.Result.DefaultSelection<Prisma.$HotSearchPayload>

export type AggregateHotSearch = {
  _count: HotSearchCountAggregateOutputType | null
  _avg: HotSearchAvgAggregateOutputType | null
  _sum: HotSearchSumAggregateOutputType | null
  _min: HotSearchMinAggregateOutputType | null
  _max: HotSearchMaxAggregateOutputType | null
}

export type HotSearchAvgAggregateOutputType = {
  id: number | null
  count: number | null
}

export type HotSearchSumAggregateOutputType = {
  id: number | null
  count: number | null
}

export type HotSearchMinAggregateOutputType = {
  id: number | null
  keyword: string | null
  type: string | null
  count: number | null
}

export type HotSearchMaxAggregateOutputType = {
  id: number | null
  keyword: string | null
  type: string | null
  count: number | null
}

export type HotSearchCountAggregateOutputType = {
  id: number
  keyword: number
  type: number
  count: number
  _all: number
}


export type HotSearchAvgAggregateInputType = {
  id?: true
  count?: true
}

export type HotSearchSumAggregateInputType = {
  id?: true
  count?: true
}

export type HotSearchMinAggregateInputType = {
  id?: true
  keyword?: true
  type?: true
  count?: true
}

export type HotSearchMaxAggregateInputType = {
  id?: true
  keyword?: true
  type?: true
  count?: true
}

export type HotSearchCountAggregateInputType = {
  id?: true
  keyword?: true
  type?: true
  count?: true
  _all?: true
}

export type HotSearchAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HotSearch to aggregate.
   */
  where?: Prisma.HotSearchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HotSearches to fetch.
   */
  orderBy?: Prisma.HotSearchOrderByWithRelationInput | Prisma.HotSearchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HotSearchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HotSearches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HotSearches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned HotSearches
  **/
  _count?: true | HotSearchCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HotSearchAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HotSearchSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HotSearchMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HotSearchMaxAggregateInputType
}

export type GetHotSearchAggregateType<T extends HotSearchAggregateArgs> = {
      [P in keyof T & keyof AggregateHotSearch]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHotSearch[P]>
    : Prisma.GetScalarType<T[P], AggregateHotSearch[P]>
}




export type HotSearchGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HotSearchWhereInput
  orderBy?: Prisma.HotSearchOrderByWithAggregationInput | Prisma.HotSearchOrderByWithAggregationInput[]
  by: Prisma.HotSearchScalarFieldEnum[] | Prisma.HotSearchScalarFieldEnum
  having?: Prisma.HotSearchScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HotSearchCountAggregateInputType | true
  _avg?: HotSearchAvgAggregateInputType
  _sum?: HotSearchSumAggregateInputType
  _min?: HotSearchMinAggregateInputType
  _max?: HotSearchMaxAggregateInputType
}

export type HotSearchGroupByOutputType = {
  id: number
  keyword: string
  type: string
  count: number
  _count: HotSearchCountAggregateOutputType | null
  _avg: HotSearchAvgAggregateOutputType | null
  _sum: HotSearchSumAggregateOutputType | null
  _min: HotSearchMinAggregateOutputType | null
  _max: HotSearchMaxAggregateOutputType | null
}

export type GetHotSearchGroupByPayload<T extends HotSearchGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HotSearchGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HotSearchGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HotSearchGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HotSearchGroupByOutputType[P]>
      }
    >
  >



export type HotSearchWhereInput = {
  AND?: Prisma.HotSearchWhereInput | Prisma.HotSearchWhereInput[]
  OR?: Prisma.HotSearchWhereInput[]
  NOT?: Prisma.HotSearchWhereInput | Prisma.HotSearchWhereInput[]
  id?: Prisma.IntFilter<"HotSearch"> | number
  keyword?: Prisma.StringFilter<"HotSearch"> | string
  type?: Prisma.StringFilter<"HotSearch"> | string
  count?: Prisma.IntFilter<"HotSearch"> | number
}

export type HotSearchOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  keyword?: Prisma.SortOrder
  type?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type HotSearchWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  keyword?: string
  AND?: Prisma.HotSearchWhereInput | Prisma.HotSearchWhereInput[]
  OR?: Prisma.HotSearchWhereInput[]
  NOT?: Prisma.HotSearchWhereInput | Prisma.HotSearchWhereInput[]
  type?: Prisma.StringFilter<"HotSearch"> | string
  count?: Prisma.IntFilter<"HotSearch"> | number
}, "id" | "keyword">

export type HotSearchOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  keyword?: Prisma.SortOrder
  type?: Prisma.SortOrder
  count?: Prisma.SortOrder
  _count?: Prisma.HotSearchCountOrderByAggregateInput
  _avg?: Prisma.HotSearchAvgOrderByAggregateInput
  _max?: Prisma.HotSearchMaxOrderByAggregateInput
  _min?: Prisma.HotSearchMinOrderByAggregateInput
  _sum?: Prisma.HotSearchSumOrderByAggregateInput
}

export type HotSearchScalarWhereWithAggregatesInput = {
  AND?: Prisma.HotSearchScalarWhereWithAggregatesInput | Prisma.HotSearchScalarWhereWithAggregatesInput[]
  OR?: Prisma.HotSearchScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HotSearchScalarWhereWithAggregatesInput | Prisma.HotSearchScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"HotSearch"> | number
  keyword?: Prisma.StringWithAggregatesFilter<"HotSearch"> | string
  type?: Prisma.StringWithAggregatesFilter<"HotSearch"> | string
  count?: Prisma.IntWithAggregatesFilter<"HotSearch"> | number
}

export type HotSearchCreateInput = {
  keyword: string
  type?: string
  count?: number
}

export type HotSearchUncheckedCreateInput = {
  id?: number
  keyword: string
  type?: string
  count?: number
}

export type HotSearchUpdateInput = {
  keyword?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HotSearchUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  keyword?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HotSearchCreateManyInput = {
  id?: number
  keyword: string
  type?: string
  count?: number
}

export type HotSearchUpdateManyMutationInput = {
  keyword?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HotSearchUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  keyword?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HotSearchCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  keyword?: Prisma.SortOrder
  type?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type HotSearchAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type HotSearchMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  keyword?: Prisma.SortOrder
  type?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type HotSearchMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  keyword?: Prisma.SortOrder
  type?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type HotSearchSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  count?: Prisma.SortOrder
}



export type HotSearchSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  keyword?: boolean
  type?: boolean
  count?: boolean
}, ExtArgs["result"]["hotSearch"]>

export type HotSearchSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  keyword?: boolean
  type?: boolean
  count?: boolean
}, ExtArgs["result"]["hotSearch"]>

export type HotSearchSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  keyword?: boolean
  type?: boolean
  count?: boolean
}, ExtArgs["result"]["hotSearch"]>

export type HotSearchSelectScalar = {
  id?: boolean
  keyword?: boolean
  type?: boolean
  count?: boolean
}

export type HotSearchOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "keyword" | "type" | "count", ExtArgs["result"]["hotSearch"]>

export type $HotSearchPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "HotSearch"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    keyword: string
    type: string
    count: number
  }, ExtArgs["result"]["hotSearch"]>
  composites: {}
}

export type HotSearchGetPayload<S extends boolean | null | undefined | HotSearchDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HotSearchPayload, S>

export type HotSearchCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HotSearchFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HotSearchCountAggregateInputType | true
  }

export interface HotSearchDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['HotSearch'], meta: { name: 'HotSearch' } }
  /**
   * Find zero or one HotSearch that matches the filter.
   * @param {HotSearchFindUniqueArgs} args - Arguments to find a HotSearch
   * @example
   * // Get one HotSearch
   * const hotSearch = await prisma.hotSearch.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HotSearchFindUniqueArgs>(args: Prisma.SelectSubset<T, HotSearchFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HotSearchClient<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one HotSearch that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HotSearchFindUniqueOrThrowArgs} args - Arguments to find a HotSearch
   * @example
   * // Get one HotSearch
   * const hotSearch = await prisma.hotSearch.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HotSearchFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HotSearchFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HotSearchClient<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HotSearch that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HotSearchFindFirstArgs} args - Arguments to find a HotSearch
   * @example
   * // Get one HotSearch
   * const hotSearch = await prisma.hotSearch.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HotSearchFindFirstArgs>(args?: Prisma.SelectSubset<T, HotSearchFindFirstArgs<ExtArgs>>): Prisma.Prisma__HotSearchClient<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HotSearch that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HotSearchFindFirstOrThrowArgs} args - Arguments to find a HotSearch
   * @example
   * // Get one HotSearch
   * const hotSearch = await prisma.hotSearch.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HotSearchFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HotSearchFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HotSearchClient<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more HotSearches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HotSearchFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all HotSearches
   * const hotSearches = await prisma.hotSearch.findMany()
   * 
   * // Get first 10 HotSearches
   * const hotSearches = await prisma.hotSearch.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const hotSearchWithIdOnly = await prisma.hotSearch.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HotSearchFindManyArgs>(args?: Prisma.SelectSubset<T, HotSearchFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a HotSearch.
   * @param {HotSearchCreateArgs} args - Arguments to create a HotSearch.
   * @example
   * // Create one HotSearch
   * const HotSearch = await prisma.hotSearch.create({
   *   data: {
   *     // ... data to create a HotSearch
   *   }
   * })
   * 
   */
  create<T extends HotSearchCreateArgs>(args: Prisma.SelectSubset<T, HotSearchCreateArgs<ExtArgs>>): Prisma.Prisma__HotSearchClient<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many HotSearches.
   * @param {HotSearchCreateManyArgs} args - Arguments to create many HotSearches.
   * @example
   * // Create many HotSearches
   * const hotSearch = await prisma.hotSearch.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HotSearchCreateManyArgs>(args?: Prisma.SelectSubset<T, HotSearchCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many HotSearches and returns the data saved in the database.
   * @param {HotSearchCreateManyAndReturnArgs} args - Arguments to create many HotSearches.
   * @example
   * // Create many HotSearches
   * const hotSearch = await prisma.hotSearch.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many HotSearches and only return the `id`
   * const hotSearchWithIdOnly = await prisma.hotSearch.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HotSearchCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HotSearchCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a HotSearch.
   * @param {HotSearchDeleteArgs} args - Arguments to delete one HotSearch.
   * @example
   * // Delete one HotSearch
   * const HotSearch = await prisma.hotSearch.delete({
   *   where: {
   *     // ... filter to delete one HotSearch
   *   }
   * })
   * 
   */
  delete<T extends HotSearchDeleteArgs>(args: Prisma.SelectSubset<T, HotSearchDeleteArgs<ExtArgs>>): Prisma.Prisma__HotSearchClient<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one HotSearch.
   * @param {HotSearchUpdateArgs} args - Arguments to update one HotSearch.
   * @example
   * // Update one HotSearch
   * const hotSearch = await prisma.hotSearch.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HotSearchUpdateArgs>(args: Prisma.SelectSubset<T, HotSearchUpdateArgs<ExtArgs>>): Prisma.Prisma__HotSearchClient<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more HotSearches.
   * @param {HotSearchDeleteManyArgs} args - Arguments to filter HotSearches to delete.
   * @example
   * // Delete a few HotSearches
   * const { count } = await prisma.hotSearch.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HotSearchDeleteManyArgs>(args?: Prisma.SelectSubset<T, HotSearchDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HotSearches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HotSearchUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many HotSearches
   * const hotSearch = await prisma.hotSearch.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HotSearchUpdateManyArgs>(args: Prisma.SelectSubset<T, HotSearchUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HotSearches and returns the data updated in the database.
   * @param {HotSearchUpdateManyAndReturnArgs} args - Arguments to update many HotSearches.
   * @example
   * // Update many HotSearches
   * const hotSearch = await prisma.hotSearch.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more HotSearches and only return the `id`
   * const hotSearchWithIdOnly = await prisma.hotSearch.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HotSearchUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HotSearchUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one HotSearch.
   * @param {HotSearchUpsertArgs} args - Arguments to update or create a HotSearch.
   * @example
   * // Update or create a HotSearch
   * const hotSearch = await prisma.hotSearch.upsert({
   *   create: {
   *     // ... data to create a HotSearch
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the HotSearch we want to update
   *   }
   * })
   */
  upsert<T extends HotSearchUpsertArgs>(args: Prisma.SelectSubset<T, HotSearchUpsertArgs<ExtArgs>>): Prisma.Prisma__HotSearchClient<runtime.Types.Result.GetResult<Prisma.$HotSearchPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of HotSearches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HotSearchCountArgs} args - Arguments to filter HotSearches to count.
   * @example
   * // Count the number of HotSearches
   * const count = await prisma.hotSearch.count({
   *   where: {
   *     // ... the filter for the HotSearches we want to count
   *   }
   * })
  **/
  count<T extends HotSearchCountArgs>(
    args?: Prisma.Subset<T, HotSearchCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HotSearchCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a HotSearch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HotSearchAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HotSearchAggregateArgs>(args: Prisma.Subset<T, HotSearchAggregateArgs>): Prisma.PrismaPromise<GetHotSearchAggregateType<T>>

  /**
   * Group by HotSearch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HotSearchGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HotSearchGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HotSearchGroupByArgs['orderBy'] }
      : { orderBy?: HotSearchGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HotSearchGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHotSearchGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the HotSearch model
 */
readonly fields: HotSearchFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for HotSearch.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HotSearchClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the HotSearch model
 */
export interface HotSearchFieldRefs {
  readonly id: Prisma.FieldRef<"HotSearch", 'Int'>
  readonly keyword: Prisma.FieldRef<"HotSearch", 'String'>
  readonly type: Prisma.FieldRef<"HotSearch", 'String'>
  readonly count: Prisma.FieldRef<"HotSearch", 'Int'>
}
    

// Custom InputTypes
/**
 * HotSearch findUnique
 */
export type HotSearchFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * Filter, which HotSearch to fetch.
   */
  where: Prisma.HotSearchWhereUniqueInput
}

/**
 * HotSearch findUniqueOrThrow
 */
export type HotSearchFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * Filter, which HotSearch to fetch.
   */
  where: Prisma.HotSearchWhereUniqueInput
}

/**
 * HotSearch findFirst
 */
export type HotSearchFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * Filter, which HotSearch to fetch.
   */
  where?: Prisma.HotSearchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HotSearches to fetch.
   */
  orderBy?: Prisma.HotSearchOrderByWithRelationInput | Prisma.HotSearchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HotSearches.
   */
  cursor?: Prisma.HotSearchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HotSearches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HotSearches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HotSearches.
   */
  distinct?: Prisma.HotSearchScalarFieldEnum | Prisma.HotSearchScalarFieldEnum[]
}

/**
 * HotSearch findFirstOrThrow
 */
export type HotSearchFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * Filter, which HotSearch to fetch.
   */
  where?: Prisma.HotSearchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HotSearches to fetch.
   */
  orderBy?: Prisma.HotSearchOrderByWithRelationInput | Prisma.HotSearchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HotSearches.
   */
  cursor?: Prisma.HotSearchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HotSearches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HotSearches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HotSearches.
   */
  distinct?: Prisma.HotSearchScalarFieldEnum | Prisma.HotSearchScalarFieldEnum[]
}

/**
 * HotSearch findMany
 */
export type HotSearchFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * Filter, which HotSearches to fetch.
   */
  where?: Prisma.HotSearchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HotSearches to fetch.
   */
  orderBy?: Prisma.HotSearchOrderByWithRelationInput | Prisma.HotSearchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing HotSearches.
   */
  cursor?: Prisma.HotSearchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HotSearches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HotSearches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HotSearches.
   */
  distinct?: Prisma.HotSearchScalarFieldEnum | Prisma.HotSearchScalarFieldEnum[]
}

/**
 * HotSearch create
 */
export type HotSearchCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * The data needed to create a HotSearch.
   */
  data: Prisma.XOR<Prisma.HotSearchCreateInput, Prisma.HotSearchUncheckedCreateInput>
}

/**
 * HotSearch createMany
 */
export type HotSearchCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many HotSearches.
   */
  data: Prisma.HotSearchCreateManyInput | Prisma.HotSearchCreateManyInput[]
}

/**
 * HotSearch createManyAndReturn
 */
export type HotSearchCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * The data used to create many HotSearches.
   */
  data: Prisma.HotSearchCreateManyInput | Prisma.HotSearchCreateManyInput[]
}

/**
 * HotSearch update
 */
export type HotSearchUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * The data needed to update a HotSearch.
   */
  data: Prisma.XOR<Prisma.HotSearchUpdateInput, Prisma.HotSearchUncheckedUpdateInput>
  /**
   * Choose, which HotSearch to update.
   */
  where: Prisma.HotSearchWhereUniqueInput
}

/**
 * HotSearch updateMany
 */
export type HotSearchUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update HotSearches.
   */
  data: Prisma.XOR<Prisma.HotSearchUpdateManyMutationInput, Prisma.HotSearchUncheckedUpdateManyInput>
  /**
   * Filter which HotSearches to update
   */
  where?: Prisma.HotSearchWhereInput
  /**
   * Limit how many HotSearches to update.
   */
  limit?: number
}

/**
 * HotSearch updateManyAndReturn
 */
export type HotSearchUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * The data used to update HotSearches.
   */
  data: Prisma.XOR<Prisma.HotSearchUpdateManyMutationInput, Prisma.HotSearchUncheckedUpdateManyInput>
  /**
   * Filter which HotSearches to update
   */
  where?: Prisma.HotSearchWhereInput
  /**
   * Limit how many HotSearches to update.
   */
  limit?: number
}

/**
 * HotSearch upsert
 */
export type HotSearchUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * The filter to search for the HotSearch to update in case it exists.
   */
  where: Prisma.HotSearchWhereUniqueInput
  /**
   * In case the HotSearch found by the `where` argument doesn't exist, create a new HotSearch with this data.
   */
  create: Prisma.XOR<Prisma.HotSearchCreateInput, Prisma.HotSearchUncheckedCreateInput>
  /**
   * In case the HotSearch was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HotSearchUpdateInput, Prisma.HotSearchUncheckedUpdateInput>
}

/**
 * HotSearch delete
 */
export type HotSearchDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
  /**
   * Filter which HotSearch to delete.
   */
  where: Prisma.HotSearchWhereUniqueInput
}

/**
 * HotSearch deleteMany
 */
export type HotSearchDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HotSearches to delete
   */
  where?: Prisma.HotSearchWhereInput
  /**
   * Limit how many HotSearches to delete.
   */
  limit?: number
}

/**
 * HotSearch without action
 */
export type HotSearchDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HotSearch
   */
  select?: Prisma.HotSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HotSearch
   */
  omit?: Prisma.HotSearchOmit<ExtArgs> | null
}
