
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SoftwareRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model SoftwareRequest
 * 
 */
export type SoftwareRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$SoftwareRequestPayload>

export type AggregateSoftwareRequest = {
  _count: SoftwareRequestCountAggregateOutputType | null
  _avg: SoftwareRequestAvgAggregateOutputType | null
  _sum: SoftwareRequestSumAggregateOutputType | null
  _min: SoftwareRequestMinAggregateOutputType | null
  _max: SoftwareRequestMaxAggregateOutputType | null
}

export type SoftwareRequestAvgAggregateOutputType = {
  id: number | null
}

export type SoftwareRequestSumAggregateOutputType = {
  id: number | null
}

export type SoftwareRequestMinAggregateOutputType = {
  id: number | null
  title: string | null
  description: string | null
  authorName: string | null
  authorEmail: string | null
  status: string | null
  createdAt: Date | null
  adminReply: string | null
  repliedAt: Date | null
}

export type SoftwareRequestMaxAggregateOutputType = {
  id: number | null
  title: string | null
  description: string | null
  authorName: string | null
  authorEmail: string | null
  status: string | null
  createdAt: Date | null
  adminReply: string | null
  repliedAt: Date | null
}

export type SoftwareRequestCountAggregateOutputType = {
  id: number
  title: number
  description: number
  authorName: number
  authorEmail: number
  status: number
  createdAt: number
  adminReply: number
  repliedAt: number
  _all: number
}


export type SoftwareRequestAvgAggregateInputType = {
  id?: true
}

export type SoftwareRequestSumAggregateInputType = {
  id?: true
}

export type SoftwareRequestMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  authorName?: true
  authorEmail?: true
  status?: true
  createdAt?: true
  adminReply?: true
  repliedAt?: true
}

export type SoftwareRequestMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  authorName?: true
  authorEmail?: true
  status?: true
  createdAt?: true
  adminReply?: true
  repliedAt?: true
}

export type SoftwareRequestCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  authorName?: true
  authorEmail?: true
  status?: true
  createdAt?: true
  adminReply?: true
  repliedAt?: true
  _all?: true
}

export type SoftwareRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SoftwareRequest to aggregate.
   */
  where?: Prisma.SoftwareRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SoftwareRequests to fetch.
   */
  orderBy?: Prisma.SoftwareRequestOrderByWithRelationInput | Prisma.SoftwareRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SoftwareRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SoftwareRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SoftwareRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SoftwareRequests
  **/
  _count?: true | SoftwareRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SoftwareRequestAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SoftwareRequestSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SoftwareRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SoftwareRequestMaxAggregateInputType
}

export type GetSoftwareRequestAggregateType<T extends SoftwareRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateSoftwareRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSoftwareRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateSoftwareRequest[P]>
}




export type SoftwareRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SoftwareRequestWhereInput
  orderBy?: Prisma.SoftwareRequestOrderByWithAggregationInput | Prisma.SoftwareRequestOrderByWithAggregationInput[]
  by: Prisma.SoftwareRequestScalarFieldEnum[] | Prisma.SoftwareRequestScalarFieldEnum
  having?: Prisma.SoftwareRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SoftwareRequestCountAggregateInputType | true
  _avg?: SoftwareRequestAvgAggregateInputType
  _sum?: SoftwareRequestSumAggregateInputType
  _min?: SoftwareRequestMinAggregateInputType
  _max?: SoftwareRequestMaxAggregateInputType
}

export type SoftwareRequestGroupByOutputType = {
  id: number
  title: string
  description: string
  authorName: string
  authorEmail: string
  status: string
  createdAt: Date
  adminReply: string | null
  repliedAt: Date | null
  _count: SoftwareRequestCountAggregateOutputType | null
  _avg: SoftwareRequestAvgAggregateOutputType | null
  _sum: SoftwareRequestSumAggregateOutputType | null
  _min: SoftwareRequestMinAggregateOutputType | null
  _max: SoftwareRequestMaxAggregateOutputType | null
}

export type GetSoftwareRequestGroupByPayload<T extends SoftwareRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SoftwareRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SoftwareRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SoftwareRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SoftwareRequestGroupByOutputType[P]>
      }
    >
  >



export type SoftwareRequestWhereInput = {
  AND?: Prisma.SoftwareRequestWhereInput | Prisma.SoftwareRequestWhereInput[]
  OR?: Prisma.SoftwareRequestWhereInput[]
  NOT?: Prisma.SoftwareRequestWhereInput | Prisma.SoftwareRequestWhereInput[]
  id?: Prisma.IntFilter<"SoftwareRequest"> | number
  title?: Prisma.StringFilter<"SoftwareRequest"> | string
  description?: Prisma.StringFilter<"SoftwareRequest"> | string
  authorName?: Prisma.StringFilter<"SoftwareRequest"> | string
  authorEmail?: Prisma.StringFilter<"SoftwareRequest"> | string
  status?: Prisma.StringFilter<"SoftwareRequest"> | string
  createdAt?: Prisma.DateTimeFilter<"SoftwareRequest"> | Date | string
  adminReply?: Prisma.StringNullableFilter<"SoftwareRequest"> | string | null
  repliedAt?: Prisma.DateTimeNullableFilter<"SoftwareRequest"> | Date | string | null
}

export type SoftwareRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorEmail?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  adminReply?: Prisma.SortOrderInput | Prisma.SortOrder
  repliedAt?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type SoftwareRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SoftwareRequestWhereInput | Prisma.SoftwareRequestWhereInput[]
  OR?: Prisma.SoftwareRequestWhereInput[]
  NOT?: Prisma.SoftwareRequestWhereInput | Prisma.SoftwareRequestWhereInput[]
  title?: Prisma.StringFilter<"SoftwareRequest"> | string
  description?: Prisma.StringFilter<"SoftwareRequest"> | string
  authorName?: Prisma.StringFilter<"SoftwareRequest"> | string
  authorEmail?: Prisma.StringFilter<"SoftwareRequest"> | string
  status?: Prisma.StringFilter<"SoftwareRequest"> | string
  createdAt?: Prisma.DateTimeFilter<"SoftwareRequest"> | Date | string
  adminReply?: Prisma.StringNullableFilter<"SoftwareRequest"> | string | null
  repliedAt?: Prisma.DateTimeNullableFilter<"SoftwareRequest"> | Date | string | null
}, "id">

export type SoftwareRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorEmail?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  adminReply?: Prisma.SortOrderInput | Prisma.SortOrder
  repliedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SoftwareRequestCountOrderByAggregateInput
  _avg?: Prisma.SoftwareRequestAvgOrderByAggregateInput
  _max?: Prisma.SoftwareRequestMaxOrderByAggregateInput
  _min?: Prisma.SoftwareRequestMinOrderByAggregateInput
  _sum?: Prisma.SoftwareRequestSumOrderByAggregateInput
}

export type SoftwareRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.SoftwareRequestScalarWhereWithAggregatesInput | Prisma.SoftwareRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.SoftwareRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SoftwareRequestScalarWhereWithAggregatesInput | Prisma.SoftwareRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"SoftwareRequest"> | number
  title?: Prisma.StringWithAggregatesFilter<"SoftwareRequest"> | string
  description?: Prisma.StringWithAggregatesFilter<"SoftwareRequest"> | string
  authorName?: Prisma.StringWithAggregatesFilter<"SoftwareRequest"> | string
  authorEmail?: Prisma.StringWithAggregatesFilter<"SoftwareRequest"> | string
  status?: Prisma.StringWithAggregatesFilter<"SoftwareRequest"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SoftwareRequest"> | Date | string
  adminReply?: Prisma.StringNullableWithAggregatesFilter<"SoftwareRequest"> | string | null
  repliedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"SoftwareRequest"> | Date | string | null
}

export type SoftwareRequestCreateInput = {
  title: string
  description: string
  authorName: string
  authorEmail: string
  status?: string
  createdAt?: Date | string
  adminReply?: string | null
  repliedAt?: Date | string | null
}

export type SoftwareRequestUncheckedCreateInput = {
  id?: number
  title: string
  description: string
  authorName: string
  authorEmail: string
  status?: string
  createdAt?: Date | string
  adminReply?: string | null
  repliedAt?: Date | string | null
}

export type SoftwareRequestUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  authorName?: Prisma.StringFieldUpdateOperationsInput | string
  authorEmail?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  adminReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repliedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SoftwareRequestUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  authorName?: Prisma.StringFieldUpdateOperationsInput | string
  authorEmail?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  adminReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repliedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SoftwareRequestCreateManyInput = {
  id?: number
  title: string
  description: string
  authorName: string
  authorEmail: string
  status?: string
  createdAt?: Date | string
  adminReply?: string | null
  repliedAt?: Date | string | null
}

export type SoftwareRequestUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  authorName?: Prisma.StringFieldUpdateOperationsInput | string
  authorEmail?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  adminReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repliedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SoftwareRequestUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  authorName?: Prisma.StringFieldUpdateOperationsInput | string
  authorEmail?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  adminReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repliedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SoftwareRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorEmail?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  adminReply?: Prisma.SortOrder
  repliedAt?: Prisma.SortOrder
}

export type SoftwareRequestAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type SoftwareRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorEmail?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  adminReply?: Prisma.SortOrder
  repliedAt?: Prisma.SortOrder
}

export type SoftwareRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorEmail?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  adminReply?: Prisma.SortOrder
  repliedAt?: Prisma.SortOrder
}

export type SoftwareRequestSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type SoftwareRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  authorName?: boolean
  authorEmail?: boolean
  status?: boolean
  createdAt?: boolean
  adminReply?: boolean
  repliedAt?: boolean
}, ExtArgs["result"]["softwareRequest"]>

export type SoftwareRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  authorName?: boolean
  authorEmail?: boolean
  status?: boolean
  createdAt?: boolean
  adminReply?: boolean
  repliedAt?: boolean
}, ExtArgs["result"]["softwareRequest"]>

export type SoftwareRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  authorName?: boolean
  authorEmail?: boolean
  status?: boolean
  createdAt?: boolean
  adminReply?: boolean
  repliedAt?: boolean
}, ExtArgs["result"]["softwareRequest"]>

export type SoftwareRequestSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  authorName?: boolean
  authorEmail?: boolean
  status?: boolean
  createdAt?: boolean
  adminReply?: boolean
  repliedAt?: boolean
}

export type SoftwareRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "authorName" | "authorEmail" | "status" | "createdAt" | "adminReply" | "repliedAt", ExtArgs["result"]["softwareRequest"]>

export type $SoftwareRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SoftwareRequest"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string
    description: string
    authorName: string
    authorEmail: string
    status: string
    createdAt: Date
    adminReply: string | null
    repliedAt: Date | null
  }, ExtArgs["result"]["softwareRequest"]>
  composites: {}
}

export type SoftwareRequestGetPayload<S extends boolean | null | undefined | SoftwareRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload, S>

export type SoftwareRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SoftwareRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SoftwareRequestCountAggregateInputType | true
  }

export interface SoftwareRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SoftwareRequest'], meta: { name: 'SoftwareRequest' } }
  /**
   * Find zero or one SoftwareRequest that matches the filter.
   * @param {SoftwareRequestFindUniqueArgs} args - Arguments to find a SoftwareRequest
   * @example
   * // Get one SoftwareRequest
   * const softwareRequest = await prisma.softwareRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SoftwareRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, SoftwareRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SoftwareRequestClient<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SoftwareRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SoftwareRequestFindUniqueOrThrowArgs} args - Arguments to find a SoftwareRequest
   * @example
   * // Get one SoftwareRequest
   * const softwareRequest = await prisma.softwareRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SoftwareRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SoftwareRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SoftwareRequestClient<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SoftwareRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SoftwareRequestFindFirstArgs} args - Arguments to find a SoftwareRequest
   * @example
   * // Get one SoftwareRequest
   * const softwareRequest = await prisma.softwareRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SoftwareRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, SoftwareRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__SoftwareRequestClient<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SoftwareRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SoftwareRequestFindFirstOrThrowArgs} args - Arguments to find a SoftwareRequest
   * @example
   * // Get one SoftwareRequest
   * const softwareRequest = await prisma.softwareRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SoftwareRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SoftwareRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SoftwareRequestClient<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SoftwareRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SoftwareRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SoftwareRequests
   * const softwareRequests = await prisma.softwareRequest.findMany()
   * 
   * // Get first 10 SoftwareRequests
   * const softwareRequests = await prisma.softwareRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const softwareRequestWithIdOnly = await prisma.softwareRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SoftwareRequestFindManyArgs>(args?: Prisma.SelectSubset<T, SoftwareRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SoftwareRequest.
   * @param {SoftwareRequestCreateArgs} args - Arguments to create a SoftwareRequest.
   * @example
   * // Create one SoftwareRequest
   * const SoftwareRequest = await prisma.softwareRequest.create({
   *   data: {
   *     // ... data to create a SoftwareRequest
   *   }
   * })
   * 
   */
  create<T extends SoftwareRequestCreateArgs>(args: Prisma.SelectSubset<T, SoftwareRequestCreateArgs<ExtArgs>>): Prisma.Prisma__SoftwareRequestClient<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SoftwareRequests.
   * @param {SoftwareRequestCreateManyArgs} args - Arguments to create many SoftwareRequests.
   * @example
   * // Create many SoftwareRequests
   * const softwareRequest = await prisma.softwareRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SoftwareRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, SoftwareRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SoftwareRequests and returns the data saved in the database.
   * @param {SoftwareRequestCreateManyAndReturnArgs} args - Arguments to create many SoftwareRequests.
   * @example
   * // Create many SoftwareRequests
   * const softwareRequest = await prisma.softwareRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SoftwareRequests and only return the `id`
   * const softwareRequestWithIdOnly = await prisma.softwareRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SoftwareRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SoftwareRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SoftwareRequest.
   * @param {SoftwareRequestDeleteArgs} args - Arguments to delete one SoftwareRequest.
   * @example
   * // Delete one SoftwareRequest
   * const SoftwareRequest = await prisma.softwareRequest.delete({
   *   where: {
   *     // ... filter to delete one SoftwareRequest
   *   }
   * })
   * 
   */
  delete<T extends SoftwareRequestDeleteArgs>(args: Prisma.SelectSubset<T, SoftwareRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__SoftwareRequestClient<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SoftwareRequest.
   * @param {SoftwareRequestUpdateArgs} args - Arguments to update one SoftwareRequest.
   * @example
   * // Update one SoftwareRequest
   * const softwareRequest = await prisma.softwareRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SoftwareRequestUpdateArgs>(args: Prisma.SelectSubset<T, SoftwareRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__SoftwareRequestClient<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SoftwareRequests.
   * @param {SoftwareRequestDeleteManyArgs} args - Arguments to filter SoftwareRequests to delete.
   * @example
   * // Delete a few SoftwareRequests
   * const { count } = await prisma.softwareRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SoftwareRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, SoftwareRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SoftwareRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SoftwareRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SoftwareRequests
   * const softwareRequest = await prisma.softwareRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SoftwareRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, SoftwareRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SoftwareRequests and returns the data updated in the database.
   * @param {SoftwareRequestUpdateManyAndReturnArgs} args - Arguments to update many SoftwareRequests.
   * @example
   * // Update many SoftwareRequests
   * const softwareRequest = await prisma.softwareRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SoftwareRequests and only return the `id`
   * const softwareRequestWithIdOnly = await prisma.softwareRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SoftwareRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SoftwareRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SoftwareRequest.
   * @param {SoftwareRequestUpsertArgs} args - Arguments to update or create a SoftwareRequest.
   * @example
   * // Update or create a SoftwareRequest
   * const softwareRequest = await prisma.softwareRequest.upsert({
   *   create: {
   *     // ... data to create a SoftwareRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SoftwareRequest we want to update
   *   }
   * })
   */
  upsert<T extends SoftwareRequestUpsertArgs>(args: Prisma.SelectSubset<T, SoftwareRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__SoftwareRequestClient<runtime.Types.Result.GetResult<Prisma.$SoftwareRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SoftwareRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SoftwareRequestCountArgs} args - Arguments to filter SoftwareRequests to count.
   * @example
   * // Count the number of SoftwareRequests
   * const count = await prisma.softwareRequest.count({
   *   where: {
   *     // ... the filter for the SoftwareRequests we want to count
   *   }
   * })
  **/
  count<T extends SoftwareRequestCountArgs>(
    args?: Prisma.Subset<T, SoftwareRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SoftwareRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SoftwareRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SoftwareRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SoftwareRequestAggregateArgs>(args: Prisma.Subset<T, SoftwareRequestAggregateArgs>): Prisma.PrismaPromise<GetSoftwareRequestAggregateType<T>>

  /**
   * Group by SoftwareRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SoftwareRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SoftwareRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SoftwareRequestGroupByArgs['orderBy'] }
      : { orderBy?: SoftwareRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SoftwareRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSoftwareRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SoftwareRequest model
 */
readonly fields: SoftwareRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SoftwareRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SoftwareRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SoftwareRequest model
 */
export interface SoftwareRequestFieldRefs {
  readonly id: Prisma.FieldRef<"SoftwareRequest", 'Int'>
  readonly title: Prisma.FieldRef<"SoftwareRequest", 'String'>
  readonly description: Prisma.FieldRef<"SoftwareRequest", 'String'>
  readonly authorName: Prisma.FieldRef<"SoftwareRequest", 'String'>
  readonly authorEmail: Prisma.FieldRef<"SoftwareRequest", 'String'>
  readonly status: Prisma.FieldRef<"SoftwareRequest", 'String'>
  readonly createdAt: Prisma.FieldRef<"SoftwareRequest", 'DateTime'>
  readonly adminReply: Prisma.FieldRef<"SoftwareRequest", 'String'>
  readonly repliedAt: Prisma.FieldRef<"SoftwareRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SoftwareRequest findUnique
 */
export type SoftwareRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * Filter, which SoftwareRequest to fetch.
   */
  where: Prisma.SoftwareRequestWhereUniqueInput
}

/**
 * SoftwareRequest findUniqueOrThrow
 */
export type SoftwareRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * Filter, which SoftwareRequest to fetch.
   */
  where: Prisma.SoftwareRequestWhereUniqueInput
}

/**
 * SoftwareRequest findFirst
 */
export type SoftwareRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * Filter, which SoftwareRequest to fetch.
   */
  where?: Prisma.SoftwareRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SoftwareRequests to fetch.
   */
  orderBy?: Prisma.SoftwareRequestOrderByWithRelationInput | Prisma.SoftwareRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SoftwareRequests.
   */
  cursor?: Prisma.SoftwareRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SoftwareRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SoftwareRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SoftwareRequests.
   */
  distinct?: Prisma.SoftwareRequestScalarFieldEnum | Prisma.SoftwareRequestScalarFieldEnum[]
}

/**
 * SoftwareRequest findFirstOrThrow
 */
export type SoftwareRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * Filter, which SoftwareRequest to fetch.
   */
  where?: Prisma.SoftwareRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SoftwareRequests to fetch.
   */
  orderBy?: Prisma.SoftwareRequestOrderByWithRelationInput | Prisma.SoftwareRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SoftwareRequests.
   */
  cursor?: Prisma.SoftwareRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SoftwareRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SoftwareRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SoftwareRequests.
   */
  distinct?: Prisma.SoftwareRequestScalarFieldEnum | Prisma.SoftwareRequestScalarFieldEnum[]
}

/**
 * SoftwareRequest findMany
 */
export type SoftwareRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * Filter, which SoftwareRequests to fetch.
   */
  where?: Prisma.SoftwareRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SoftwareRequests to fetch.
   */
  orderBy?: Prisma.SoftwareRequestOrderByWithRelationInput | Prisma.SoftwareRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SoftwareRequests.
   */
  cursor?: Prisma.SoftwareRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SoftwareRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SoftwareRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SoftwareRequests.
   */
  distinct?: Prisma.SoftwareRequestScalarFieldEnum | Prisma.SoftwareRequestScalarFieldEnum[]
}

/**
 * SoftwareRequest create
 */
export type SoftwareRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * The data needed to create a SoftwareRequest.
   */
  data: Prisma.XOR<Prisma.SoftwareRequestCreateInput, Prisma.SoftwareRequestUncheckedCreateInput>
}

/**
 * SoftwareRequest createMany
 */
export type SoftwareRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SoftwareRequests.
   */
  data: Prisma.SoftwareRequestCreateManyInput | Prisma.SoftwareRequestCreateManyInput[]
}

/**
 * SoftwareRequest createManyAndReturn
 */
export type SoftwareRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * The data used to create many SoftwareRequests.
   */
  data: Prisma.SoftwareRequestCreateManyInput | Prisma.SoftwareRequestCreateManyInput[]
}

/**
 * SoftwareRequest update
 */
export type SoftwareRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * The data needed to update a SoftwareRequest.
   */
  data: Prisma.XOR<Prisma.SoftwareRequestUpdateInput, Prisma.SoftwareRequestUncheckedUpdateInput>
  /**
   * Choose, which SoftwareRequest to update.
   */
  where: Prisma.SoftwareRequestWhereUniqueInput
}

/**
 * SoftwareRequest updateMany
 */
export type SoftwareRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SoftwareRequests.
   */
  data: Prisma.XOR<Prisma.SoftwareRequestUpdateManyMutationInput, Prisma.SoftwareRequestUncheckedUpdateManyInput>
  /**
   * Filter which SoftwareRequests to update
   */
  where?: Prisma.SoftwareRequestWhereInput
  /**
   * Limit how many SoftwareRequests to update.
   */
  limit?: number
}

/**
 * SoftwareRequest updateManyAndReturn
 */
export type SoftwareRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * The data used to update SoftwareRequests.
   */
  data: Prisma.XOR<Prisma.SoftwareRequestUpdateManyMutationInput, Prisma.SoftwareRequestUncheckedUpdateManyInput>
  /**
   * Filter which SoftwareRequests to update
   */
  where?: Prisma.SoftwareRequestWhereInput
  /**
   * Limit how many SoftwareRequests to update.
   */
  limit?: number
}

/**
 * SoftwareRequest upsert
 */
export type SoftwareRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * The filter to search for the SoftwareRequest to update in case it exists.
   */
  where: Prisma.SoftwareRequestWhereUniqueInput
  /**
   * In case the SoftwareRequest found by the `where` argument doesn't exist, create a new SoftwareRequest with this data.
   */
  create: Prisma.XOR<Prisma.SoftwareRequestCreateInput, Prisma.SoftwareRequestUncheckedCreateInput>
  /**
   * In case the SoftwareRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SoftwareRequestUpdateInput, Prisma.SoftwareRequestUncheckedUpdateInput>
}

/**
 * SoftwareRequest delete
 */
export type SoftwareRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
  /**
   * Filter which SoftwareRequest to delete.
   */
  where: Prisma.SoftwareRequestWhereUniqueInput
}

/**
 * SoftwareRequest deleteMany
 */
export type SoftwareRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SoftwareRequests to delete
   */
  where?: Prisma.SoftwareRequestWhereInput
  /**
   * Limit how many SoftwareRequests to delete.
   */
  limit?: number
}

/**
 * SoftwareRequest without action
 */
export type SoftwareRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SoftwareRequest
   */
  select?: Prisma.SoftwareRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SoftwareRequest
   */
  omit?: Prisma.SoftwareRequestOmit<ExtArgs> | null
}
