
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TopicApp` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TopicApp
 * 
 */
export type TopicAppModel = runtime.Types.Result.DefaultSelection<Prisma.$TopicAppPayload>

export type AggregateTopicApp = {
  _count: TopicAppCountAggregateOutputType | null
  _avg: TopicAppAvgAggregateOutputType | null
  _sum: TopicAppSumAggregateOutputType | null
  _min: TopicAppMinAggregateOutputType | null
  _max: TopicAppMaxAggregateOutputType | null
}

export type TopicAppAvgAggregateOutputType = {
  topicId: number | null
}

export type TopicAppSumAggregateOutputType = {
  topicId: number | null
}

export type TopicAppMinAggregateOutputType = {
  topicId: number | null
  appSlug: string | null
}

export type TopicAppMaxAggregateOutputType = {
  topicId: number | null
  appSlug: string | null
}

export type TopicAppCountAggregateOutputType = {
  topicId: number
  appSlug: number
  _all: number
}


export type TopicAppAvgAggregateInputType = {
  topicId?: true
}

export type TopicAppSumAggregateInputType = {
  topicId?: true
}

export type TopicAppMinAggregateInputType = {
  topicId?: true
  appSlug?: true
}

export type TopicAppMaxAggregateInputType = {
  topicId?: true
  appSlug?: true
}

export type TopicAppCountAggregateInputType = {
  topicId?: true
  appSlug?: true
  _all?: true
}

export type TopicAppAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TopicApp to aggregate.
   */
  where?: Prisma.TopicAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopicApps to fetch.
   */
  orderBy?: Prisma.TopicAppOrderByWithRelationInput | Prisma.TopicAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TopicAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopicApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopicApps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TopicApps
  **/
  _count?: true | TopicAppCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TopicAppAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TopicAppSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TopicAppMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TopicAppMaxAggregateInputType
}

export type GetTopicAppAggregateType<T extends TopicAppAggregateArgs> = {
      [P in keyof T & keyof AggregateTopicApp]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTopicApp[P]>
    : Prisma.GetScalarType<T[P], AggregateTopicApp[P]>
}




export type TopicAppGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TopicAppWhereInput
  orderBy?: Prisma.TopicAppOrderByWithAggregationInput | Prisma.TopicAppOrderByWithAggregationInput[]
  by: Prisma.TopicAppScalarFieldEnum[] | Prisma.TopicAppScalarFieldEnum
  having?: Prisma.TopicAppScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TopicAppCountAggregateInputType | true
  _avg?: TopicAppAvgAggregateInputType
  _sum?: TopicAppSumAggregateInputType
  _min?: TopicAppMinAggregateInputType
  _max?: TopicAppMaxAggregateInputType
}

export type TopicAppGroupByOutputType = {
  topicId: number
  appSlug: string
  _count: TopicAppCountAggregateOutputType | null
  _avg: TopicAppAvgAggregateOutputType | null
  _sum: TopicAppSumAggregateOutputType | null
  _min: TopicAppMinAggregateOutputType | null
  _max: TopicAppMaxAggregateOutputType | null
}

export type GetTopicAppGroupByPayload<T extends TopicAppGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TopicAppGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TopicAppGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TopicAppGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TopicAppGroupByOutputType[P]>
      }
    >
  >



export type TopicAppWhereInput = {
  AND?: Prisma.TopicAppWhereInput | Prisma.TopicAppWhereInput[]
  OR?: Prisma.TopicAppWhereInput[]
  NOT?: Prisma.TopicAppWhereInput | Prisma.TopicAppWhereInput[]
  topicId?: Prisma.IntFilter<"TopicApp"> | number
  appSlug?: Prisma.StringFilter<"TopicApp"> | string
  topic?: Prisma.XOR<Prisma.TopicScalarRelationFilter, Prisma.TopicWhereInput>
  app?: Prisma.XOR<Prisma.AppScalarRelationFilter, Prisma.AppWhereInput>
}

export type TopicAppOrderByWithRelationInput = {
  topicId?: Prisma.SortOrder
  appSlug?: Prisma.SortOrder
  topic?: Prisma.TopicOrderByWithRelationInput
  app?: Prisma.AppOrderByWithRelationInput
}

export type TopicAppWhereUniqueInput = Prisma.AtLeast<{
  topicId_appSlug?: Prisma.TopicAppTopicIdAppSlugCompoundUniqueInput
  AND?: Prisma.TopicAppWhereInput | Prisma.TopicAppWhereInput[]
  OR?: Prisma.TopicAppWhereInput[]
  NOT?: Prisma.TopicAppWhereInput | Prisma.TopicAppWhereInput[]
  topicId?: Prisma.IntFilter<"TopicApp"> | number
  appSlug?: Prisma.StringFilter<"TopicApp"> | string
  topic?: Prisma.XOR<Prisma.TopicScalarRelationFilter, Prisma.TopicWhereInput>
  app?: Prisma.XOR<Prisma.AppScalarRelationFilter, Prisma.AppWhereInput>
}, "topicId_appSlug">

export type TopicAppOrderByWithAggregationInput = {
  topicId?: Prisma.SortOrder
  appSlug?: Prisma.SortOrder
  _count?: Prisma.TopicAppCountOrderByAggregateInput
  _avg?: Prisma.TopicAppAvgOrderByAggregateInput
  _max?: Prisma.TopicAppMaxOrderByAggregateInput
  _min?: Prisma.TopicAppMinOrderByAggregateInput
  _sum?: Prisma.TopicAppSumOrderByAggregateInput
}

export type TopicAppScalarWhereWithAggregatesInput = {
  AND?: Prisma.TopicAppScalarWhereWithAggregatesInput | Prisma.TopicAppScalarWhereWithAggregatesInput[]
  OR?: Prisma.TopicAppScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TopicAppScalarWhereWithAggregatesInput | Prisma.TopicAppScalarWhereWithAggregatesInput[]
  topicId?: Prisma.IntWithAggregatesFilter<"TopicApp"> | number
  appSlug?: Prisma.StringWithAggregatesFilter<"TopicApp"> | string
}

export type TopicAppCreateInput = {
  topic: Prisma.TopicCreateNestedOneWithoutRelatedAppsInput
  app: Prisma.AppCreateNestedOneWithoutTopicsInput
}

export type TopicAppUncheckedCreateInput = {
  topicId: number
  appSlug: string
}

export type TopicAppUpdateInput = {
  topic?: Prisma.TopicUpdateOneRequiredWithoutRelatedAppsNestedInput
  app?: Prisma.AppUpdateOneRequiredWithoutTopicsNestedInput
}

export type TopicAppUncheckedUpdateInput = {
  topicId?: Prisma.IntFieldUpdateOperationsInput | number
  appSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TopicAppCreateManyInput = {
  topicId: number
  appSlug: string
}

export type TopicAppUpdateManyMutationInput = {

}

export type TopicAppUncheckedUpdateManyInput = {
  topicId?: Prisma.IntFieldUpdateOperationsInput | number
  appSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TopicAppListRelationFilter = {
  every?: Prisma.TopicAppWhereInput
  some?: Prisma.TopicAppWhereInput
  none?: Prisma.TopicAppWhereInput
}

export type TopicAppOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TopicAppTopicIdAppSlugCompoundUniqueInput = {
  topicId: number
  appSlug: string
}

export type TopicAppCountOrderByAggregateInput = {
  topicId?: Prisma.SortOrder
  appSlug?: Prisma.SortOrder
}

export type TopicAppAvgOrderByAggregateInput = {
  topicId?: Prisma.SortOrder
}

export type TopicAppMaxOrderByAggregateInput = {
  topicId?: Prisma.SortOrder
  appSlug?: Prisma.SortOrder
}

export type TopicAppMinOrderByAggregateInput = {
  topicId?: Prisma.SortOrder
  appSlug?: Prisma.SortOrder
}

export type TopicAppSumOrderByAggregateInput = {
  topicId?: Prisma.SortOrder
}

export type TopicAppCreateNestedManyWithoutAppInput = {
  create?: Prisma.XOR<Prisma.TopicAppCreateWithoutAppInput, Prisma.TopicAppUncheckedCreateWithoutAppInput> | Prisma.TopicAppCreateWithoutAppInput[] | Prisma.TopicAppUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.TopicAppCreateOrConnectWithoutAppInput | Prisma.TopicAppCreateOrConnectWithoutAppInput[]
  createMany?: Prisma.TopicAppCreateManyAppInputEnvelope
  connect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
}

export type TopicAppUncheckedCreateNestedManyWithoutAppInput = {
  create?: Prisma.XOR<Prisma.TopicAppCreateWithoutAppInput, Prisma.TopicAppUncheckedCreateWithoutAppInput> | Prisma.TopicAppCreateWithoutAppInput[] | Prisma.TopicAppUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.TopicAppCreateOrConnectWithoutAppInput | Prisma.TopicAppCreateOrConnectWithoutAppInput[]
  createMany?: Prisma.TopicAppCreateManyAppInputEnvelope
  connect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
}

export type TopicAppUpdateManyWithoutAppNestedInput = {
  create?: Prisma.XOR<Prisma.TopicAppCreateWithoutAppInput, Prisma.TopicAppUncheckedCreateWithoutAppInput> | Prisma.TopicAppCreateWithoutAppInput[] | Prisma.TopicAppUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.TopicAppCreateOrConnectWithoutAppInput | Prisma.TopicAppCreateOrConnectWithoutAppInput[]
  upsert?: Prisma.TopicAppUpsertWithWhereUniqueWithoutAppInput | Prisma.TopicAppUpsertWithWhereUniqueWithoutAppInput[]
  createMany?: Prisma.TopicAppCreateManyAppInputEnvelope
  set?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  disconnect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  delete?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  connect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  update?: Prisma.TopicAppUpdateWithWhereUniqueWithoutAppInput | Prisma.TopicAppUpdateWithWhereUniqueWithoutAppInput[]
  updateMany?: Prisma.TopicAppUpdateManyWithWhereWithoutAppInput | Prisma.TopicAppUpdateManyWithWhereWithoutAppInput[]
  deleteMany?: Prisma.TopicAppScalarWhereInput | Prisma.TopicAppScalarWhereInput[]
}

export type TopicAppUncheckedUpdateManyWithoutAppNestedInput = {
  create?: Prisma.XOR<Prisma.TopicAppCreateWithoutAppInput, Prisma.TopicAppUncheckedCreateWithoutAppInput> | Prisma.TopicAppCreateWithoutAppInput[] | Prisma.TopicAppUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.TopicAppCreateOrConnectWithoutAppInput | Prisma.TopicAppCreateOrConnectWithoutAppInput[]
  upsert?: Prisma.TopicAppUpsertWithWhereUniqueWithoutAppInput | Prisma.TopicAppUpsertWithWhereUniqueWithoutAppInput[]
  createMany?: Prisma.TopicAppCreateManyAppInputEnvelope
  set?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  disconnect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  delete?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  connect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  update?: Prisma.TopicAppUpdateWithWhereUniqueWithoutAppInput | Prisma.TopicAppUpdateWithWhereUniqueWithoutAppInput[]
  updateMany?: Prisma.TopicAppUpdateManyWithWhereWithoutAppInput | Prisma.TopicAppUpdateManyWithWhereWithoutAppInput[]
  deleteMany?: Prisma.TopicAppScalarWhereInput | Prisma.TopicAppScalarWhereInput[]
}

export type TopicAppCreateNestedManyWithoutTopicInput = {
  create?: Prisma.XOR<Prisma.TopicAppCreateWithoutTopicInput, Prisma.TopicAppUncheckedCreateWithoutTopicInput> | Prisma.TopicAppCreateWithoutTopicInput[] | Prisma.TopicAppUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.TopicAppCreateOrConnectWithoutTopicInput | Prisma.TopicAppCreateOrConnectWithoutTopicInput[]
  createMany?: Prisma.TopicAppCreateManyTopicInputEnvelope
  connect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
}

export type TopicAppUncheckedCreateNestedManyWithoutTopicInput = {
  create?: Prisma.XOR<Prisma.TopicAppCreateWithoutTopicInput, Prisma.TopicAppUncheckedCreateWithoutTopicInput> | Prisma.TopicAppCreateWithoutTopicInput[] | Prisma.TopicAppUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.TopicAppCreateOrConnectWithoutTopicInput | Prisma.TopicAppCreateOrConnectWithoutTopicInput[]
  createMany?: Prisma.TopicAppCreateManyTopicInputEnvelope
  connect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
}

export type TopicAppUpdateManyWithoutTopicNestedInput = {
  create?: Prisma.XOR<Prisma.TopicAppCreateWithoutTopicInput, Prisma.TopicAppUncheckedCreateWithoutTopicInput> | Prisma.TopicAppCreateWithoutTopicInput[] | Prisma.TopicAppUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.TopicAppCreateOrConnectWithoutTopicInput | Prisma.TopicAppCreateOrConnectWithoutTopicInput[]
  upsert?: Prisma.TopicAppUpsertWithWhereUniqueWithoutTopicInput | Prisma.TopicAppUpsertWithWhereUniqueWithoutTopicInput[]
  createMany?: Prisma.TopicAppCreateManyTopicInputEnvelope
  set?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  disconnect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  delete?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  connect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  update?: Prisma.TopicAppUpdateWithWhereUniqueWithoutTopicInput | Prisma.TopicAppUpdateWithWhereUniqueWithoutTopicInput[]
  updateMany?: Prisma.TopicAppUpdateManyWithWhereWithoutTopicInput | Prisma.TopicAppUpdateManyWithWhereWithoutTopicInput[]
  deleteMany?: Prisma.TopicAppScalarWhereInput | Prisma.TopicAppScalarWhereInput[]
}

export type TopicAppUncheckedUpdateManyWithoutTopicNestedInput = {
  create?: Prisma.XOR<Prisma.TopicAppCreateWithoutTopicInput, Prisma.TopicAppUncheckedCreateWithoutTopicInput> | Prisma.TopicAppCreateWithoutTopicInput[] | Prisma.TopicAppUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.TopicAppCreateOrConnectWithoutTopicInput | Prisma.TopicAppCreateOrConnectWithoutTopicInput[]
  upsert?: Prisma.TopicAppUpsertWithWhereUniqueWithoutTopicInput | Prisma.TopicAppUpsertWithWhereUniqueWithoutTopicInput[]
  createMany?: Prisma.TopicAppCreateManyTopicInputEnvelope
  set?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  disconnect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  delete?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  connect?: Prisma.TopicAppWhereUniqueInput | Prisma.TopicAppWhereUniqueInput[]
  update?: Prisma.TopicAppUpdateWithWhereUniqueWithoutTopicInput | Prisma.TopicAppUpdateWithWhereUniqueWithoutTopicInput[]
  updateMany?: Prisma.TopicAppUpdateManyWithWhereWithoutTopicInput | Prisma.TopicAppUpdateManyWithWhereWithoutTopicInput[]
  deleteMany?: Prisma.TopicAppScalarWhereInput | Prisma.TopicAppScalarWhereInput[]
}

export type TopicAppCreateWithoutAppInput = {
  topic: Prisma.TopicCreateNestedOneWithoutRelatedAppsInput
}

export type TopicAppUncheckedCreateWithoutAppInput = {
  topicId: number
}

export type TopicAppCreateOrConnectWithoutAppInput = {
  where: Prisma.TopicAppWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicAppCreateWithoutAppInput, Prisma.TopicAppUncheckedCreateWithoutAppInput>
}

export type TopicAppCreateManyAppInputEnvelope = {
  data: Prisma.TopicAppCreateManyAppInput | Prisma.TopicAppCreateManyAppInput[]
}

export type TopicAppUpsertWithWhereUniqueWithoutAppInput = {
  where: Prisma.TopicAppWhereUniqueInput
  update: Prisma.XOR<Prisma.TopicAppUpdateWithoutAppInput, Prisma.TopicAppUncheckedUpdateWithoutAppInput>
  create: Prisma.XOR<Prisma.TopicAppCreateWithoutAppInput, Prisma.TopicAppUncheckedCreateWithoutAppInput>
}

export type TopicAppUpdateWithWhereUniqueWithoutAppInput = {
  where: Prisma.TopicAppWhereUniqueInput
  data: Prisma.XOR<Prisma.TopicAppUpdateWithoutAppInput, Prisma.TopicAppUncheckedUpdateWithoutAppInput>
}

export type TopicAppUpdateManyWithWhereWithoutAppInput = {
  where: Prisma.TopicAppScalarWhereInput
  data: Prisma.XOR<Prisma.TopicAppUpdateManyMutationInput, Prisma.TopicAppUncheckedUpdateManyWithoutAppInput>
}

export type TopicAppScalarWhereInput = {
  AND?: Prisma.TopicAppScalarWhereInput | Prisma.TopicAppScalarWhereInput[]
  OR?: Prisma.TopicAppScalarWhereInput[]
  NOT?: Prisma.TopicAppScalarWhereInput | Prisma.TopicAppScalarWhereInput[]
  topicId?: Prisma.IntFilter<"TopicApp"> | number
  appSlug?: Prisma.StringFilter<"TopicApp"> | string
}

export type TopicAppCreateWithoutTopicInput = {
  app: Prisma.AppCreateNestedOneWithoutTopicsInput
}

export type TopicAppUncheckedCreateWithoutTopicInput = {
  appSlug: string
}

export type TopicAppCreateOrConnectWithoutTopicInput = {
  where: Prisma.TopicAppWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicAppCreateWithoutTopicInput, Prisma.TopicAppUncheckedCreateWithoutTopicInput>
}

export type TopicAppCreateManyTopicInputEnvelope = {
  data: Prisma.TopicAppCreateManyTopicInput | Prisma.TopicAppCreateManyTopicInput[]
}

export type TopicAppUpsertWithWhereUniqueWithoutTopicInput = {
  where: Prisma.TopicAppWhereUniqueInput
  update: Prisma.XOR<Prisma.TopicAppUpdateWithoutTopicInput, Prisma.TopicAppUncheckedUpdateWithoutTopicInput>
  create: Prisma.XOR<Prisma.TopicAppCreateWithoutTopicInput, Prisma.TopicAppUncheckedCreateWithoutTopicInput>
}

export type TopicAppUpdateWithWhereUniqueWithoutTopicInput = {
  where: Prisma.TopicAppWhereUniqueInput
  data: Prisma.XOR<Prisma.TopicAppUpdateWithoutTopicInput, Prisma.TopicAppUncheckedUpdateWithoutTopicInput>
}

export type TopicAppUpdateManyWithWhereWithoutTopicInput = {
  where: Prisma.TopicAppScalarWhereInput
  data: Prisma.XOR<Prisma.TopicAppUpdateManyMutationInput, Prisma.TopicAppUncheckedUpdateManyWithoutTopicInput>
}

export type TopicAppCreateManyAppInput = {
  topicId: number
}

export type TopicAppUpdateWithoutAppInput = {
  topic?: Prisma.TopicUpdateOneRequiredWithoutRelatedAppsNestedInput
}

export type TopicAppUncheckedUpdateWithoutAppInput = {
  topicId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopicAppUncheckedUpdateManyWithoutAppInput = {
  topicId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopicAppCreateManyTopicInput = {
  appSlug: string
}

export type TopicAppUpdateWithoutTopicInput = {
  app?: Prisma.AppUpdateOneRequiredWithoutTopicsNestedInput
}

export type TopicAppUncheckedUpdateWithoutTopicInput = {
  appSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TopicAppUncheckedUpdateManyWithoutTopicInput = {
  appSlug?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TopicAppSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  topicId?: boolean
  appSlug?: boolean
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topicApp"]>

export type TopicAppSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  topicId?: boolean
  appSlug?: boolean
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topicApp"]>

export type TopicAppSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  topicId?: boolean
  appSlug?: boolean
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topicApp"]>

export type TopicAppSelectScalar = {
  topicId?: boolean
  appSlug?: boolean
}

export type TopicAppOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"topicId" | "appSlug", ExtArgs["result"]["topicApp"]>
export type TopicAppInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}
export type TopicAppIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}
export type TopicAppIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}

export type $TopicAppPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TopicApp"
  objects: {
    topic: Prisma.$TopicPayload<ExtArgs>
    app: Prisma.$AppPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    topicId: number
    appSlug: string
  }, ExtArgs["result"]["topicApp"]>
  composites: {}
}

export type TopicAppGetPayload<S extends boolean | null | undefined | TopicAppDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TopicAppPayload, S>

export type TopicAppCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TopicAppFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TopicAppCountAggregateInputType | true
  }

export interface TopicAppDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TopicApp'], meta: { name: 'TopicApp' } }
  /**
   * Find zero or one TopicApp that matches the filter.
   * @param {TopicAppFindUniqueArgs} args - Arguments to find a TopicApp
   * @example
   * // Get one TopicApp
   * const topicApp = await prisma.topicApp.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TopicAppFindUniqueArgs>(args: Prisma.SelectSubset<T, TopicAppFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TopicAppClient<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TopicApp that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TopicAppFindUniqueOrThrowArgs} args - Arguments to find a TopicApp
   * @example
   * // Get one TopicApp
   * const topicApp = await prisma.topicApp.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TopicAppFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TopicAppFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TopicAppClient<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TopicApp that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicAppFindFirstArgs} args - Arguments to find a TopicApp
   * @example
   * // Get one TopicApp
   * const topicApp = await prisma.topicApp.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TopicAppFindFirstArgs>(args?: Prisma.SelectSubset<T, TopicAppFindFirstArgs<ExtArgs>>): Prisma.Prisma__TopicAppClient<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TopicApp that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicAppFindFirstOrThrowArgs} args - Arguments to find a TopicApp
   * @example
   * // Get one TopicApp
   * const topicApp = await prisma.topicApp.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TopicAppFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TopicAppFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TopicAppClient<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TopicApps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicAppFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TopicApps
   * const topicApps = await prisma.topicApp.findMany()
   * 
   * // Get first 10 TopicApps
   * const topicApps = await prisma.topicApp.findMany({ take: 10 })
   * 
   * // Only select the `topicId`
   * const topicAppWithTopicIdOnly = await prisma.topicApp.findMany({ select: { topicId: true } })
   * 
   */
  findMany<T extends TopicAppFindManyArgs>(args?: Prisma.SelectSubset<T, TopicAppFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TopicApp.
   * @param {TopicAppCreateArgs} args - Arguments to create a TopicApp.
   * @example
   * // Create one TopicApp
   * const TopicApp = await prisma.topicApp.create({
   *   data: {
   *     // ... data to create a TopicApp
   *   }
   * })
   * 
   */
  create<T extends TopicAppCreateArgs>(args: Prisma.SelectSubset<T, TopicAppCreateArgs<ExtArgs>>): Prisma.Prisma__TopicAppClient<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TopicApps.
   * @param {TopicAppCreateManyArgs} args - Arguments to create many TopicApps.
   * @example
   * // Create many TopicApps
   * const topicApp = await prisma.topicApp.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TopicAppCreateManyArgs>(args?: Prisma.SelectSubset<T, TopicAppCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TopicApps and returns the data saved in the database.
   * @param {TopicAppCreateManyAndReturnArgs} args - Arguments to create many TopicApps.
   * @example
   * // Create many TopicApps
   * const topicApp = await prisma.topicApp.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TopicApps and only return the `topicId`
   * const topicAppWithTopicIdOnly = await prisma.topicApp.createManyAndReturn({
   *   select: { topicId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TopicAppCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TopicAppCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TopicApp.
   * @param {TopicAppDeleteArgs} args - Arguments to delete one TopicApp.
   * @example
   * // Delete one TopicApp
   * const TopicApp = await prisma.topicApp.delete({
   *   where: {
   *     // ... filter to delete one TopicApp
   *   }
   * })
   * 
   */
  delete<T extends TopicAppDeleteArgs>(args: Prisma.SelectSubset<T, TopicAppDeleteArgs<ExtArgs>>): Prisma.Prisma__TopicAppClient<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TopicApp.
   * @param {TopicAppUpdateArgs} args - Arguments to update one TopicApp.
   * @example
   * // Update one TopicApp
   * const topicApp = await prisma.topicApp.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TopicAppUpdateArgs>(args: Prisma.SelectSubset<T, TopicAppUpdateArgs<ExtArgs>>): Prisma.Prisma__TopicAppClient<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TopicApps.
   * @param {TopicAppDeleteManyArgs} args - Arguments to filter TopicApps to delete.
   * @example
   * // Delete a few TopicApps
   * const { count } = await prisma.topicApp.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TopicAppDeleteManyArgs>(args?: Prisma.SelectSubset<T, TopicAppDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TopicApps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicAppUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TopicApps
   * const topicApp = await prisma.topicApp.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TopicAppUpdateManyArgs>(args: Prisma.SelectSubset<T, TopicAppUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TopicApps and returns the data updated in the database.
   * @param {TopicAppUpdateManyAndReturnArgs} args - Arguments to update many TopicApps.
   * @example
   * // Update many TopicApps
   * const topicApp = await prisma.topicApp.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TopicApps and only return the `topicId`
   * const topicAppWithTopicIdOnly = await prisma.topicApp.updateManyAndReturn({
   *   select: { topicId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TopicAppUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TopicAppUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TopicApp.
   * @param {TopicAppUpsertArgs} args - Arguments to update or create a TopicApp.
   * @example
   * // Update or create a TopicApp
   * const topicApp = await prisma.topicApp.upsert({
   *   create: {
   *     // ... data to create a TopicApp
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TopicApp we want to update
   *   }
   * })
   */
  upsert<T extends TopicAppUpsertArgs>(args: Prisma.SelectSubset<T, TopicAppUpsertArgs<ExtArgs>>): Prisma.Prisma__TopicAppClient<runtime.Types.Result.GetResult<Prisma.$TopicAppPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TopicApps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicAppCountArgs} args - Arguments to filter TopicApps to count.
   * @example
   * // Count the number of TopicApps
   * const count = await prisma.topicApp.count({
   *   where: {
   *     // ... the filter for the TopicApps we want to count
   *   }
   * })
  **/
  count<T extends TopicAppCountArgs>(
    args?: Prisma.Subset<T, TopicAppCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TopicAppCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TopicApp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicAppAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TopicAppAggregateArgs>(args: Prisma.Subset<T, TopicAppAggregateArgs>): Prisma.PrismaPromise<GetTopicAppAggregateType<T>>

  /**
   * Group by TopicApp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicAppGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TopicAppGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TopicAppGroupByArgs['orderBy'] }
      : { orderBy?: TopicAppGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TopicAppGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTopicAppGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TopicApp model
 */
readonly fields: TopicAppFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TopicApp.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TopicAppClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  topic<T extends Prisma.TopicDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TopicDefaultArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  app<T extends Prisma.AppDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppDefaultArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TopicApp model
 */
export interface TopicAppFieldRefs {
  readonly topicId: Prisma.FieldRef<"TopicApp", 'Int'>
  readonly appSlug: Prisma.FieldRef<"TopicApp", 'String'>
}
    

// Custom InputTypes
/**
 * TopicApp findUnique
 */
export type TopicAppFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppInclude<ExtArgs> | null
  /**
   * Filter, which TopicApp to fetch.
   */
  where: Prisma.TopicAppWhereUniqueInput
}

/**
 * TopicApp findUniqueOrThrow
 */
export type TopicAppFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppInclude<ExtArgs> | null
  /**
   * Filter, which TopicApp to fetch.
   */
  where: Prisma.TopicAppWhereUniqueInput
}

/**
 * TopicApp findFirst
 */
export type TopicAppFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppInclude<ExtArgs> | null
  /**
   * Filter, which TopicApp to fetch.
   */
  where?: Prisma.TopicAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopicApps to fetch.
   */
  orderBy?: Prisma.TopicAppOrderByWithRelationInput | Prisma.TopicAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TopicApps.
   */
  cursor?: Prisma.TopicAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopicApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopicApps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TopicApps.
   */
  distinct?: Prisma.TopicAppScalarFieldEnum | Prisma.TopicAppScalarFieldEnum[]
}

/**
 * TopicApp findFirstOrThrow
 */
export type TopicAppFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppInclude<ExtArgs> | null
  /**
   * Filter, which TopicApp to fetch.
   */
  where?: Prisma.TopicAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopicApps to fetch.
   */
  orderBy?: Prisma.TopicAppOrderByWithRelationInput | Prisma.TopicAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TopicApps.
   */
  cursor?: Prisma.TopicAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopicApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopicApps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TopicApps.
   */
  distinct?: Prisma.TopicAppScalarFieldEnum | Prisma.TopicAppScalarFieldEnum[]
}

/**
 * TopicApp findMany
 */
export type TopicAppFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppInclude<ExtArgs> | null
  /**
   * Filter, which TopicApps to fetch.
   */
  where?: Prisma.TopicAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopicApps to fetch.
   */
  orderBy?: Prisma.TopicAppOrderByWithRelationInput | Prisma.TopicAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TopicApps.
   */
  cursor?: Prisma.TopicAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopicApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopicApps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TopicApps.
   */
  distinct?: Prisma.TopicAppScalarFieldEnum | Prisma.TopicAppScalarFieldEnum[]
}

/**
 * TopicApp create
 */
export type TopicAppCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppInclude<ExtArgs> | null
  /**
   * The data needed to create a TopicApp.
   */
  data: Prisma.XOR<Prisma.TopicAppCreateInput, Prisma.TopicAppUncheckedCreateInput>
}

/**
 * TopicApp createMany
 */
export type TopicAppCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TopicApps.
   */
  data: Prisma.TopicAppCreateManyInput | Prisma.TopicAppCreateManyInput[]
}

/**
 * TopicApp createManyAndReturn
 */
export type TopicAppCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * The data used to create many TopicApps.
   */
  data: Prisma.TopicAppCreateManyInput | Prisma.TopicAppCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TopicApp update
 */
export type TopicAppUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppInclude<ExtArgs> | null
  /**
   * The data needed to update a TopicApp.
   */
  data: Prisma.XOR<Prisma.TopicAppUpdateInput, Prisma.TopicAppUncheckedUpdateInput>
  /**
   * Choose, which TopicApp to update.
   */
  where: Prisma.TopicAppWhereUniqueInput
}

/**
 * TopicApp updateMany
 */
export type TopicAppUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TopicApps.
   */
  data: Prisma.XOR<Prisma.TopicAppUpdateManyMutationInput, Prisma.TopicAppUncheckedUpdateManyInput>
  /**
   * Filter which TopicApps to update
   */
  where?: Prisma.TopicAppWhereInput
  /**
   * Limit how many TopicApps to update.
   */
  limit?: number
}

/**
 * TopicApp updateManyAndReturn
 */
export type TopicAppUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * The data used to update TopicApps.
   */
  data: Prisma.XOR<Prisma.TopicAppUpdateManyMutationInput, Prisma.TopicAppUncheckedUpdateManyInput>
  /**
   * Filter which TopicApps to update
   */
  where?: Prisma.TopicAppWhereInput
  /**
   * Limit how many TopicApps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TopicApp upsert
 */
export type TopicAppUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppInclude<ExtArgs> | null
  /**
   * The filter to search for the TopicApp to update in case it exists.
   */
  where: Prisma.TopicAppWhereUniqueInput
  /**
   * In case the TopicApp found by the `where` argument doesn't exist, create a new TopicApp with this data.
   */
  create: Prisma.XOR<Prisma.TopicAppCreateInput, Prisma.TopicAppUncheckedCreateInput>
  /**
   * In case the TopicApp was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TopicAppUpdateInput, Prisma.TopicAppUncheckedUpdateInput>
}

/**
 * TopicApp delete
 */
export type TopicAppDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppInclude<ExtArgs> | null
  /**
   * Filter which TopicApp to delete.
   */
  where: Prisma.TopicAppWhereUniqueInput
}

/**
 * TopicApp deleteMany
 */
export type TopicAppDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TopicApps to delete
   */
  where?: Prisma.TopicAppWhereInput
  /**
   * Limit how many TopicApps to delete.
   */
  limit?: number
}

/**
 * TopicApp without action
 */
export type TopicAppDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicApp
   */
  select?: Prisma.TopicAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicApp
   */
  omit?: Prisma.TopicAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicAppInclude<ExtArgs> | null
}
