
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TopicPost` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TopicPost
 * 
 */
export type TopicPostModel = runtime.Types.Result.DefaultSelection<Prisma.$TopicPostPayload>

export type AggregateTopicPost = {
  _count: TopicPostCountAggregateOutputType | null
  _avg: TopicPostAvgAggregateOutputType | null
  _sum: TopicPostSumAggregateOutputType | null
  _min: TopicPostMinAggregateOutputType | null
  _max: TopicPostMaxAggregateOutputType | null
}

export type TopicPostAvgAggregateOutputType = {
  topicId: number | null
}

export type TopicPostSumAggregateOutputType = {
  topicId: number | null
}

export type TopicPostMinAggregateOutputType = {
  topicId: number | null
  postSlug: string | null
}

export type TopicPostMaxAggregateOutputType = {
  topicId: number | null
  postSlug: string | null
}

export type TopicPostCountAggregateOutputType = {
  topicId: number
  postSlug: number
  _all: number
}


export type TopicPostAvgAggregateInputType = {
  topicId?: true
}

export type TopicPostSumAggregateInputType = {
  topicId?: true
}

export type TopicPostMinAggregateInputType = {
  topicId?: true
  postSlug?: true
}

export type TopicPostMaxAggregateInputType = {
  topicId?: true
  postSlug?: true
}

export type TopicPostCountAggregateInputType = {
  topicId?: true
  postSlug?: true
  _all?: true
}

export type TopicPostAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TopicPost to aggregate.
   */
  where?: Prisma.TopicPostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopicPosts to fetch.
   */
  orderBy?: Prisma.TopicPostOrderByWithRelationInput | Prisma.TopicPostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TopicPostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopicPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopicPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TopicPosts
  **/
  _count?: true | TopicPostCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TopicPostAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TopicPostSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TopicPostMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TopicPostMaxAggregateInputType
}

export type GetTopicPostAggregateType<T extends TopicPostAggregateArgs> = {
      [P in keyof T & keyof AggregateTopicPost]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTopicPost[P]>
    : Prisma.GetScalarType<T[P], AggregateTopicPost[P]>
}




export type TopicPostGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TopicPostWhereInput
  orderBy?: Prisma.TopicPostOrderByWithAggregationInput | Prisma.TopicPostOrderByWithAggregationInput[]
  by: Prisma.TopicPostScalarFieldEnum[] | Prisma.TopicPostScalarFieldEnum
  having?: Prisma.TopicPostScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TopicPostCountAggregateInputType | true
  _avg?: TopicPostAvgAggregateInputType
  _sum?: TopicPostSumAggregateInputType
  _min?: TopicPostMinAggregateInputType
  _max?: TopicPostMaxAggregateInputType
}

export type TopicPostGroupByOutputType = {
  topicId: number
  postSlug: string
  _count: TopicPostCountAggregateOutputType | null
  _avg: TopicPostAvgAggregateOutputType | null
  _sum: TopicPostSumAggregateOutputType | null
  _min: TopicPostMinAggregateOutputType | null
  _max: TopicPostMaxAggregateOutputType | null
}

export type GetTopicPostGroupByPayload<T extends TopicPostGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TopicPostGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TopicPostGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TopicPostGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TopicPostGroupByOutputType[P]>
      }
    >
  >



export type TopicPostWhereInput = {
  AND?: Prisma.TopicPostWhereInput | Prisma.TopicPostWhereInput[]
  OR?: Prisma.TopicPostWhereInput[]
  NOT?: Prisma.TopicPostWhereInput | Prisma.TopicPostWhereInput[]
  topicId?: Prisma.IntFilter<"TopicPost"> | number
  postSlug?: Prisma.StringFilter<"TopicPost"> | string
  topic?: Prisma.XOR<Prisma.TopicScalarRelationFilter, Prisma.TopicWhereInput>
  post?: Prisma.XOR<Prisma.PostScalarRelationFilter, Prisma.PostWhereInput>
}

export type TopicPostOrderByWithRelationInput = {
  topicId?: Prisma.SortOrder
  postSlug?: Prisma.SortOrder
  topic?: Prisma.TopicOrderByWithRelationInput
  post?: Prisma.PostOrderByWithRelationInput
}

export type TopicPostWhereUniqueInput = Prisma.AtLeast<{
  topicId_postSlug?: Prisma.TopicPostTopicIdPostSlugCompoundUniqueInput
  AND?: Prisma.TopicPostWhereInput | Prisma.TopicPostWhereInput[]
  OR?: Prisma.TopicPostWhereInput[]
  NOT?: Prisma.TopicPostWhereInput | Prisma.TopicPostWhereInput[]
  topicId?: Prisma.IntFilter<"TopicPost"> | number
  postSlug?: Prisma.StringFilter<"TopicPost"> | string
  topic?: Prisma.XOR<Prisma.TopicScalarRelationFilter, Prisma.TopicWhereInput>
  post?: Prisma.XOR<Prisma.PostScalarRelationFilter, Prisma.PostWhereInput>
}, "topicId_postSlug">

export type TopicPostOrderByWithAggregationInput = {
  topicId?: Prisma.SortOrder
  postSlug?: Prisma.SortOrder
  _count?: Prisma.TopicPostCountOrderByAggregateInput
  _avg?: Prisma.TopicPostAvgOrderByAggregateInput
  _max?: Prisma.TopicPostMaxOrderByAggregateInput
  _min?: Prisma.TopicPostMinOrderByAggregateInput
  _sum?: Prisma.TopicPostSumOrderByAggregateInput
}

export type TopicPostScalarWhereWithAggregatesInput = {
  AND?: Prisma.TopicPostScalarWhereWithAggregatesInput | Prisma.TopicPostScalarWhereWithAggregatesInput[]
  OR?: Prisma.TopicPostScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TopicPostScalarWhereWithAggregatesInput | Prisma.TopicPostScalarWhereWithAggregatesInput[]
  topicId?: Prisma.IntWithAggregatesFilter<"TopicPost"> | number
  postSlug?: Prisma.StringWithAggregatesFilter<"TopicPost"> | string
}

export type TopicPostCreateInput = {
  topic: Prisma.TopicCreateNestedOneWithoutRelatedPostsInput
  post: Prisma.PostCreateNestedOneWithoutTopicsInput
}

export type TopicPostUncheckedCreateInput = {
  topicId: number
  postSlug: string
}

export type TopicPostUpdateInput = {
  topic?: Prisma.TopicUpdateOneRequiredWithoutRelatedPostsNestedInput
  post?: Prisma.PostUpdateOneRequiredWithoutTopicsNestedInput
}

export type TopicPostUncheckedUpdateInput = {
  topicId?: Prisma.IntFieldUpdateOperationsInput | number
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TopicPostCreateManyInput = {
  topicId: number
  postSlug: string
}

export type TopicPostUpdateManyMutationInput = {

}

export type TopicPostUncheckedUpdateManyInput = {
  topicId?: Prisma.IntFieldUpdateOperationsInput | number
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TopicPostListRelationFilter = {
  every?: Prisma.TopicPostWhereInput
  some?: Prisma.TopicPostWhereInput
  none?: Prisma.TopicPostWhereInput
}

export type TopicPostOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TopicPostTopicIdPostSlugCompoundUniqueInput = {
  topicId: number
  postSlug: string
}

export type TopicPostCountOrderByAggregateInput = {
  topicId?: Prisma.SortOrder
  postSlug?: Prisma.SortOrder
}

export type TopicPostAvgOrderByAggregateInput = {
  topicId?: Prisma.SortOrder
}

export type TopicPostMaxOrderByAggregateInput = {
  topicId?: Prisma.SortOrder
  postSlug?: Prisma.SortOrder
}

export type TopicPostMinOrderByAggregateInput = {
  topicId?: Prisma.SortOrder
  postSlug?: Prisma.SortOrder
}

export type TopicPostSumOrderByAggregateInput = {
  topicId?: Prisma.SortOrder
}

export type TopicPostCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.TopicPostCreateWithoutPostInput, Prisma.TopicPostUncheckedCreateWithoutPostInput> | Prisma.TopicPostCreateWithoutPostInput[] | Prisma.TopicPostUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.TopicPostCreateOrConnectWithoutPostInput | Prisma.TopicPostCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.TopicPostCreateManyPostInputEnvelope
  connect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
}

export type TopicPostUncheckedCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.TopicPostCreateWithoutPostInput, Prisma.TopicPostUncheckedCreateWithoutPostInput> | Prisma.TopicPostCreateWithoutPostInput[] | Prisma.TopicPostUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.TopicPostCreateOrConnectWithoutPostInput | Prisma.TopicPostCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.TopicPostCreateManyPostInputEnvelope
  connect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
}

export type TopicPostUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.TopicPostCreateWithoutPostInput, Prisma.TopicPostUncheckedCreateWithoutPostInput> | Prisma.TopicPostCreateWithoutPostInput[] | Prisma.TopicPostUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.TopicPostCreateOrConnectWithoutPostInput | Prisma.TopicPostCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.TopicPostUpsertWithWhereUniqueWithoutPostInput | Prisma.TopicPostUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.TopicPostCreateManyPostInputEnvelope
  set?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  disconnect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  delete?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  connect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  update?: Prisma.TopicPostUpdateWithWhereUniqueWithoutPostInput | Prisma.TopicPostUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.TopicPostUpdateManyWithWhereWithoutPostInput | Prisma.TopicPostUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.TopicPostScalarWhereInput | Prisma.TopicPostScalarWhereInput[]
}

export type TopicPostUncheckedUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.TopicPostCreateWithoutPostInput, Prisma.TopicPostUncheckedCreateWithoutPostInput> | Prisma.TopicPostCreateWithoutPostInput[] | Prisma.TopicPostUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.TopicPostCreateOrConnectWithoutPostInput | Prisma.TopicPostCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.TopicPostUpsertWithWhereUniqueWithoutPostInput | Prisma.TopicPostUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.TopicPostCreateManyPostInputEnvelope
  set?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  disconnect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  delete?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  connect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  update?: Prisma.TopicPostUpdateWithWhereUniqueWithoutPostInput | Prisma.TopicPostUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.TopicPostUpdateManyWithWhereWithoutPostInput | Prisma.TopicPostUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.TopicPostScalarWhereInput | Prisma.TopicPostScalarWhereInput[]
}

export type TopicPostCreateNestedManyWithoutTopicInput = {
  create?: Prisma.XOR<Prisma.TopicPostCreateWithoutTopicInput, Prisma.TopicPostUncheckedCreateWithoutTopicInput> | Prisma.TopicPostCreateWithoutTopicInput[] | Prisma.TopicPostUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.TopicPostCreateOrConnectWithoutTopicInput | Prisma.TopicPostCreateOrConnectWithoutTopicInput[]
  createMany?: Prisma.TopicPostCreateManyTopicInputEnvelope
  connect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
}

export type TopicPostUncheckedCreateNestedManyWithoutTopicInput = {
  create?: Prisma.XOR<Prisma.TopicPostCreateWithoutTopicInput, Prisma.TopicPostUncheckedCreateWithoutTopicInput> | Prisma.TopicPostCreateWithoutTopicInput[] | Prisma.TopicPostUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.TopicPostCreateOrConnectWithoutTopicInput | Prisma.TopicPostCreateOrConnectWithoutTopicInput[]
  createMany?: Prisma.TopicPostCreateManyTopicInputEnvelope
  connect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
}

export type TopicPostUpdateManyWithoutTopicNestedInput = {
  create?: Prisma.XOR<Prisma.TopicPostCreateWithoutTopicInput, Prisma.TopicPostUncheckedCreateWithoutTopicInput> | Prisma.TopicPostCreateWithoutTopicInput[] | Prisma.TopicPostUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.TopicPostCreateOrConnectWithoutTopicInput | Prisma.TopicPostCreateOrConnectWithoutTopicInput[]
  upsert?: Prisma.TopicPostUpsertWithWhereUniqueWithoutTopicInput | Prisma.TopicPostUpsertWithWhereUniqueWithoutTopicInput[]
  createMany?: Prisma.TopicPostCreateManyTopicInputEnvelope
  set?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  disconnect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  delete?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  connect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  update?: Prisma.TopicPostUpdateWithWhereUniqueWithoutTopicInput | Prisma.TopicPostUpdateWithWhereUniqueWithoutTopicInput[]
  updateMany?: Prisma.TopicPostUpdateManyWithWhereWithoutTopicInput | Prisma.TopicPostUpdateManyWithWhereWithoutTopicInput[]
  deleteMany?: Prisma.TopicPostScalarWhereInput | Prisma.TopicPostScalarWhereInput[]
}

export type TopicPostUncheckedUpdateManyWithoutTopicNestedInput = {
  create?: Prisma.XOR<Prisma.TopicPostCreateWithoutTopicInput, Prisma.TopicPostUncheckedCreateWithoutTopicInput> | Prisma.TopicPostCreateWithoutTopicInput[] | Prisma.TopicPostUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.TopicPostCreateOrConnectWithoutTopicInput | Prisma.TopicPostCreateOrConnectWithoutTopicInput[]
  upsert?: Prisma.TopicPostUpsertWithWhereUniqueWithoutTopicInput | Prisma.TopicPostUpsertWithWhereUniqueWithoutTopicInput[]
  createMany?: Prisma.TopicPostCreateManyTopicInputEnvelope
  set?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  disconnect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  delete?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  connect?: Prisma.TopicPostWhereUniqueInput | Prisma.TopicPostWhereUniqueInput[]
  update?: Prisma.TopicPostUpdateWithWhereUniqueWithoutTopicInput | Prisma.TopicPostUpdateWithWhereUniqueWithoutTopicInput[]
  updateMany?: Prisma.TopicPostUpdateManyWithWhereWithoutTopicInput | Prisma.TopicPostUpdateManyWithWhereWithoutTopicInput[]
  deleteMany?: Prisma.TopicPostScalarWhereInput | Prisma.TopicPostScalarWhereInput[]
}

export type TopicPostCreateWithoutPostInput = {
  topic: Prisma.TopicCreateNestedOneWithoutRelatedPostsInput
}

export type TopicPostUncheckedCreateWithoutPostInput = {
  topicId: number
}

export type TopicPostCreateOrConnectWithoutPostInput = {
  where: Prisma.TopicPostWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicPostCreateWithoutPostInput, Prisma.TopicPostUncheckedCreateWithoutPostInput>
}

export type TopicPostCreateManyPostInputEnvelope = {
  data: Prisma.TopicPostCreateManyPostInput | Prisma.TopicPostCreateManyPostInput[]
}

export type TopicPostUpsertWithWhereUniqueWithoutPostInput = {
  where: Prisma.TopicPostWhereUniqueInput
  update: Prisma.XOR<Prisma.TopicPostUpdateWithoutPostInput, Prisma.TopicPostUncheckedUpdateWithoutPostInput>
  create: Prisma.XOR<Prisma.TopicPostCreateWithoutPostInput, Prisma.TopicPostUncheckedCreateWithoutPostInput>
}

export type TopicPostUpdateWithWhereUniqueWithoutPostInput = {
  where: Prisma.TopicPostWhereUniqueInput
  data: Prisma.XOR<Prisma.TopicPostUpdateWithoutPostInput, Prisma.TopicPostUncheckedUpdateWithoutPostInput>
}

export type TopicPostUpdateManyWithWhereWithoutPostInput = {
  where: Prisma.TopicPostScalarWhereInput
  data: Prisma.XOR<Prisma.TopicPostUpdateManyMutationInput, Prisma.TopicPostUncheckedUpdateManyWithoutPostInput>
}

export type TopicPostScalarWhereInput = {
  AND?: Prisma.TopicPostScalarWhereInput | Prisma.TopicPostScalarWhereInput[]
  OR?: Prisma.TopicPostScalarWhereInput[]
  NOT?: Prisma.TopicPostScalarWhereInput | Prisma.TopicPostScalarWhereInput[]
  topicId?: Prisma.IntFilter<"TopicPost"> | number
  postSlug?: Prisma.StringFilter<"TopicPost"> | string
}

export type TopicPostCreateWithoutTopicInput = {
  post: Prisma.PostCreateNestedOneWithoutTopicsInput
}

export type TopicPostUncheckedCreateWithoutTopicInput = {
  postSlug: string
}

export type TopicPostCreateOrConnectWithoutTopicInput = {
  where: Prisma.TopicPostWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicPostCreateWithoutTopicInput, Prisma.TopicPostUncheckedCreateWithoutTopicInput>
}

export type TopicPostCreateManyTopicInputEnvelope = {
  data: Prisma.TopicPostCreateManyTopicInput | Prisma.TopicPostCreateManyTopicInput[]
}

export type TopicPostUpsertWithWhereUniqueWithoutTopicInput = {
  where: Prisma.TopicPostWhereUniqueInput
  update: Prisma.XOR<Prisma.TopicPostUpdateWithoutTopicInput, Prisma.TopicPostUncheckedUpdateWithoutTopicInput>
  create: Prisma.XOR<Prisma.TopicPostCreateWithoutTopicInput, Prisma.TopicPostUncheckedCreateWithoutTopicInput>
}

export type TopicPostUpdateWithWhereUniqueWithoutTopicInput = {
  where: Prisma.TopicPostWhereUniqueInput
  data: Prisma.XOR<Prisma.TopicPostUpdateWithoutTopicInput, Prisma.TopicPostUncheckedUpdateWithoutTopicInput>
}

export type TopicPostUpdateManyWithWhereWithoutTopicInput = {
  where: Prisma.TopicPostScalarWhereInput
  data: Prisma.XOR<Prisma.TopicPostUpdateManyMutationInput, Prisma.TopicPostUncheckedUpdateManyWithoutTopicInput>
}

export type TopicPostCreateManyPostInput = {
  topicId: number
}

export type TopicPostUpdateWithoutPostInput = {
  topic?: Prisma.TopicUpdateOneRequiredWithoutRelatedPostsNestedInput
}

export type TopicPostUncheckedUpdateWithoutPostInput = {
  topicId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopicPostUncheckedUpdateManyWithoutPostInput = {
  topicId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopicPostCreateManyTopicInput = {
  postSlug: string
}

export type TopicPostUpdateWithoutTopicInput = {
  post?: Prisma.PostUpdateOneRequiredWithoutTopicsNestedInput
}

export type TopicPostUncheckedUpdateWithoutTopicInput = {
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TopicPostUncheckedUpdateManyWithoutTopicInput = {
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TopicPostSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  topicId?: boolean
  postSlug?: boolean
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topicPost"]>

export type TopicPostSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  topicId?: boolean
  postSlug?: boolean
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topicPost"]>

export type TopicPostSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  topicId?: boolean
  postSlug?: boolean
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topicPost"]>

export type TopicPostSelectScalar = {
  topicId?: boolean
  postSlug?: boolean
}

export type TopicPostOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"topicId" | "postSlug", ExtArgs["result"]["topicPost"]>
export type TopicPostInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}
export type TopicPostIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}
export type TopicPostIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topic?: boolean | Prisma.TopicDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}

export type $TopicPostPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TopicPost"
  objects: {
    topic: Prisma.$TopicPayload<ExtArgs>
    post: Prisma.$PostPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    topicId: number
    postSlug: string
  }, ExtArgs["result"]["topicPost"]>
  composites: {}
}

export type TopicPostGetPayload<S extends boolean | null | undefined | TopicPostDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TopicPostPayload, S>

export type TopicPostCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TopicPostFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TopicPostCountAggregateInputType | true
  }

export interface TopicPostDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TopicPost'], meta: { name: 'TopicPost' } }
  /**
   * Find zero or one TopicPost that matches the filter.
   * @param {TopicPostFindUniqueArgs} args - Arguments to find a TopicPost
   * @example
   * // Get one TopicPost
   * const topicPost = await prisma.topicPost.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TopicPostFindUniqueArgs>(args: Prisma.SelectSubset<T, TopicPostFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TopicPostClient<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TopicPost that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TopicPostFindUniqueOrThrowArgs} args - Arguments to find a TopicPost
   * @example
   * // Get one TopicPost
   * const topicPost = await prisma.topicPost.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TopicPostFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TopicPostFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TopicPostClient<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TopicPost that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicPostFindFirstArgs} args - Arguments to find a TopicPost
   * @example
   * // Get one TopicPost
   * const topicPost = await prisma.topicPost.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TopicPostFindFirstArgs>(args?: Prisma.SelectSubset<T, TopicPostFindFirstArgs<ExtArgs>>): Prisma.Prisma__TopicPostClient<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TopicPost that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicPostFindFirstOrThrowArgs} args - Arguments to find a TopicPost
   * @example
   * // Get one TopicPost
   * const topicPost = await prisma.topicPost.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TopicPostFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TopicPostFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TopicPostClient<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TopicPosts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicPostFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TopicPosts
   * const topicPosts = await prisma.topicPost.findMany()
   * 
   * // Get first 10 TopicPosts
   * const topicPosts = await prisma.topicPost.findMany({ take: 10 })
   * 
   * // Only select the `topicId`
   * const topicPostWithTopicIdOnly = await prisma.topicPost.findMany({ select: { topicId: true } })
   * 
   */
  findMany<T extends TopicPostFindManyArgs>(args?: Prisma.SelectSubset<T, TopicPostFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TopicPost.
   * @param {TopicPostCreateArgs} args - Arguments to create a TopicPost.
   * @example
   * // Create one TopicPost
   * const TopicPost = await prisma.topicPost.create({
   *   data: {
   *     // ... data to create a TopicPost
   *   }
   * })
   * 
   */
  create<T extends TopicPostCreateArgs>(args: Prisma.SelectSubset<T, TopicPostCreateArgs<ExtArgs>>): Prisma.Prisma__TopicPostClient<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TopicPosts.
   * @param {TopicPostCreateManyArgs} args - Arguments to create many TopicPosts.
   * @example
   * // Create many TopicPosts
   * const topicPost = await prisma.topicPost.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TopicPostCreateManyArgs>(args?: Prisma.SelectSubset<T, TopicPostCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TopicPosts and returns the data saved in the database.
   * @param {TopicPostCreateManyAndReturnArgs} args - Arguments to create many TopicPosts.
   * @example
   * // Create many TopicPosts
   * const topicPost = await prisma.topicPost.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TopicPosts and only return the `topicId`
   * const topicPostWithTopicIdOnly = await prisma.topicPost.createManyAndReturn({
   *   select: { topicId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TopicPostCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TopicPostCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TopicPost.
   * @param {TopicPostDeleteArgs} args - Arguments to delete one TopicPost.
   * @example
   * // Delete one TopicPost
   * const TopicPost = await prisma.topicPost.delete({
   *   where: {
   *     // ... filter to delete one TopicPost
   *   }
   * })
   * 
   */
  delete<T extends TopicPostDeleteArgs>(args: Prisma.SelectSubset<T, TopicPostDeleteArgs<ExtArgs>>): Prisma.Prisma__TopicPostClient<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TopicPost.
   * @param {TopicPostUpdateArgs} args - Arguments to update one TopicPost.
   * @example
   * // Update one TopicPost
   * const topicPost = await prisma.topicPost.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TopicPostUpdateArgs>(args: Prisma.SelectSubset<T, TopicPostUpdateArgs<ExtArgs>>): Prisma.Prisma__TopicPostClient<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TopicPosts.
   * @param {TopicPostDeleteManyArgs} args - Arguments to filter TopicPosts to delete.
   * @example
   * // Delete a few TopicPosts
   * const { count } = await prisma.topicPost.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TopicPostDeleteManyArgs>(args?: Prisma.SelectSubset<T, TopicPostDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TopicPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicPostUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TopicPosts
   * const topicPost = await prisma.topicPost.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TopicPostUpdateManyArgs>(args: Prisma.SelectSubset<T, TopicPostUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TopicPosts and returns the data updated in the database.
   * @param {TopicPostUpdateManyAndReturnArgs} args - Arguments to update many TopicPosts.
   * @example
   * // Update many TopicPosts
   * const topicPost = await prisma.topicPost.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TopicPosts and only return the `topicId`
   * const topicPostWithTopicIdOnly = await prisma.topicPost.updateManyAndReturn({
   *   select: { topicId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TopicPostUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TopicPostUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TopicPost.
   * @param {TopicPostUpsertArgs} args - Arguments to update or create a TopicPost.
   * @example
   * // Update or create a TopicPost
   * const topicPost = await prisma.topicPost.upsert({
   *   create: {
   *     // ... data to create a TopicPost
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TopicPost we want to update
   *   }
   * })
   */
  upsert<T extends TopicPostUpsertArgs>(args: Prisma.SelectSubset<T, TopicPostUpsertArgs<ExtArgs>>): Prisma.Prisma__TopicPostClient<runtime.Types.Result.GetResult<Prisma.$TopicPostPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TopicPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicPostCountArgs} args - Arguments to filter TopicPosts to count.
   * @example
   * // Count the number of TopicPosts
   * const count = await prisma.topicPost.count({
   *   where: {
   *     // ... the filter for the TopicPosts we want to count
   *   }
   * })
  **/
  count<T extends TopicPostCountArgs>(
    args?: Prisma.Subset<T, TopicPostCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TopicPostCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TopicPost.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicPostAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TopicPostAggregateArgs>(args: Prisma.Subset<T, TopicPostAggregateArgs>): Prisma.PrismaPromise<GetTopicPostAggregateType<T>>

  /**
   * Group by TopicPost.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicPostGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TopicPostGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TopicPostGroupByArgs['orderBy'] }
      : { orderBy?: TopicPostGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TopicPostGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTopicPostGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TopicPost model
 */
readonly fields: TopicPostFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TopicPost.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TopicPostClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  topic<T extends Prisma.TopicDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TopicDefaultArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  post<T extends Prisma.PostDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PostDefaultArgs<ExtArgs>>): Prisma.Prisma__PostClient<runtime.Types.Result.GetResult<Prisma.$PostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TopicPost model
 */
export interface TopicPostFieldRefs {
  readonly topicId: Prisma.FieldRef<"TopicPost", 'Int'>
  readonly postSlug: Prisma.FieldRef<"TopicPost", 'String'>
}
    

// Custom InputTypes
/**
 * TopicPost findUnique
 */
export type TopicPostFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostInclude<ExtArgs> | null
  /**
   * Filter, which TopicPost to fetch.
   */
  where: Prisma.TopicPostWhereUniqueInput
}

/**
 * TopicPost findUniqueOrThrow
 */
export type TopicPostFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostInclude<ExtArgs> | null
  /**
   * Filter, which TopicPost to fetch.
   */
  where: Prisma.TopicPostWhereUniqueInput
}

/**
 * TopicPost findFirst
 */
export type TopicPostFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostInclude<ExtArgs> | null
  /**
   * Filter, which TopicPost to fetch.
   */
  where?: Prisma.TopicPostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopicPosts to fetch.
   */
  orderBy?: Prisma.TopicPostOrderByWithRelationInput | Prisma.TopicPostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TopicPosts.
   */
  cursor?: Prisma.TopicPostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopicPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopicPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TopicPosts.
   */
  distinct?: Prisma.TopicPostScalarFieldEnum | Prisma.TopicPostScalarFieldEnum[]
}

/**
 * TopicPost findFirstOrThrow
 */
export type TopicPostFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostInclude<ExtArgs> | null
  /**
   * Filter, which TopicPost to fetch.
   */
  where?: Prisma.TopicPostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopicPosts to fetch.
   */
  orderBy?: Prisma.TopicPostOrderByWithRelationInput | Prisma.TopicPostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TopicPosts.
   */
  cursor?: Prisma.TopicPostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopicPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopicPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TopicPosts.
   */
  distinct?: Prisma.TopicPostScalarFieldEnum | Prisma.TopicPostScalarFieldEnum[]
}

/**
 * TopicPost findMany
 */
export type TopicPostFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostInclude<ExtArgs> | null
  /**
   * Filter, which TopicPosts to fetch.
   */
  where?: Prisma.TopicPostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopicPosts to fetch.
   */
  orderBy?: Prisma.TopicPostOrderByWithRelationInput | Prisma.TopicPostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TopicPosts.
   */
  cursor?: Prisma.TopicPostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopicPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopicPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TopicPosts.
   */
  distinct?: Prisma.TopicPostScalarFieldEnum | Prisma.TopicPostScalarFieldEnum[]
}

/**
 * TopicPost create
 */
export type TopicPostCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostInclude<ExtArgs> | null
  /**
   * The data needed to create a TopicPost.
   */
  data: Prisma.XOR<Prisma.TopicPostCreateInput, Prisma.TopicPostUncheckedCreateInput>
}

/**
 * TopicPost createMany
 */
export type TopicPostCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TopicPosts.
   */
  data: Prisma.TopicPostCreateManyInput | Prisma.TopicPostCreateManyInput[]
}

/**
 * TopicPost createManyAndReturn
 */
export type TopicPostCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * The data used to create many TopicPosts.
   */
  data: Prisma.TopicPostCreateManyInput | Prisma.TopicPostCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TopicPost update
 */
export type TopicPostUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostInclude<ExtArgs> | null
  /**
   * The data needed to update a TopicPost.
   */
  data: Prisma.XOR<Prisma.TopicPostUpdateInput, Prisma.TopicPostUncheckedUpdateInput>
  /**
   * Choose, which TopicPost to update.
   */
  where: Prisma.TopicPostWhereUniqueInput
}

/**
 * TopicPost updateMany
 */
export type TopicPostUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TopicPosts.
   */
  data: Prisma.XOR<Prisma.TopicPostUpdateManyMutationInput, Prisma.TopicPostUncheckedUpdateManyInput>
  /**
   * Filter which TopicPosts to update
   */
  where?: Prisma.TopicPostWhereInput
  /**
   * Limit how many TopicPosts to update.
   */
  limit?: number
}

/**
 * TopicPost updateManyAndReturn
 */
export type TopicPostUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * The data used to update TopicPosts.
   */
  data: Prisma.XOR<Prisma.TopicPostUpdateManyMutationInput, Prisma.TopicPostUncheckedUpdateManyInput>
  /**
   * Filter which TopicPosts to update
   */
  where?: Prisma.TopicPostWhereInput
  /**
   * Limit how many TopicPosts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TopicPost upsert
 */
export type TopicPostUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostInclude<ExtArgs> | null
  /**
   * The filter to search for the TopicPost to update in case it exists.
   */
  where: Prisma.TopicPostWhereUniqueInput
  /**
   * In case the TopicPost found by the `where` argument doesn't exist, create a new TopicPost with this data.
   */
  create: Prisma.XOR<Prisma.TopicPostCreateInput, Prisma.TopicPostUncheckedCreateInput>
  /**
   * In case the TopicPost was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TopicPostUpdateInput, Prisma.TopicPostUncheckedUpdateInput>
}

/**
 * TopicPost delete
 */
export type TopicPostDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostInclude<ExtArgs> | null
  /**
   * Filter which TopicPost to delete.
   */
  where: Prisma.TopicPostWhereUniqueInput
}

/**
 * TopicPost deleteMany
 */
export type TopicPostDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TopicPosts to delete
   */
  where?: Prisma.TopicPostWhereInput
  /**
   * Limit how many TopicPosts to delete.
   */
  limit?: number
}

/**
 * TopicPost without action
 */
export type TopicPostDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicPost
   */
  select?: Prisma.TopicPostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopicPost
   */
  omit?: Prisma.TopicPostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicPostInclude<ExtArgs> | null
}
