import prisma from './prisma.js';
import { executeRaw, queryRaw } from './dbRaw.js';

let ensured = false;

export function getDatabaseProvider() {
  const directProvider = String(
    process.env.DATABASE_PROVIDER ||
    process.env['\uFEFFDATABASE_PROVIDER'] ||
    ''
  )
    .trim()
    .toLowerCase();

  if (directProvider) {
    return directProvider;
  }

  const candidateUrls = [
    process.env.DATABASE_URL,
    process.env.DATABASE_URL_LOCAL,
    process.env.DATABASE_URL_PRODUCTION,
    process.env.DATABASE_URL_STAGING,
    process.env.DATABASE_URL_TEST,
  ]
    .map((value) => String(value || '').trim().toLowerCase())
    .filter(Boolean);

  if (candidateUrls.some((value) => value.startsWith('postgres://') || value.startsWith('postgresql://'))) {
    return 'postgresql';
  }

  return 'sqlite';
}

export function isPostgresDatabase() {
  return getDatabaseProvider() === 'postgresql';
}

export async function listTableColumns(table) {
  if (isPostgresDatabase()) {
    return queryRaw(
      `
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = ?
          AND table_schema = current_schema()
      `,
      table,
    );
  }

  return prisma.$queryRawUnsafe(`PRAGMA table_info(${table})`);
}

async function hasColumn(table, column) {
  const rows = await listTableColumns(table);
  const normalizedTarget = String(column || '').trim().toLowerCase();
  return rows.some((row) =>
    String(row.column_name || row.name || '')
      .trim()
      .toLowerCase() === normalizedTarget
  );
}

async function ensureColumn(table, column, sqliteDefinition, postgresDefinition = sqliteDefinition) {
  if (await hasColumn(table, column)) {
    return;
  }

  const definition = isPostgresDatabase() ? postgresDefinition : sqliteDefinition;
  if (isPostgresDatabase()) {
    await executeRaw(`ALTER TABLE ${table} ADD COLUMN "${column}" ${definition}`);
    return;
  }

  await executeRaw(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
}

async function ensureBaseTables() {
  if (isPostgresDatabase()) {
    await executeRaw(`
      CREATE TABLE IF NOT EXISTS sign_devices (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "userId" INTEGER NOT NULL,
        udid TEXT NOT NULL,
        product TEXT,
        version TEXT,
        "deviceName" TEXT,
        source TEXT DEFAULT 'profile_service',
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await executeRaw(`
      CREATE UNIQUE INDEX IF NOT EXISTS idx_sign_devices_user_udid
      ON sign_devices ("userId", udid)
    `);

    await executeRaw(`
      CREATE TABLE IF NOT EXISTS sign_tasks (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "userId" INTEGER NOT NULL,
        "deviceId" INTEGER,
        "certificateId" INTEGER,
        "profileId" INTEGER,
        status TEXT NOT NULL DEFAULT 'queued',
        progress INTEGER NOT NULL DEFAULT 0,
        stage TEXT DEFAULT 'waiting',
        "ipaName" TEXT,
        "ipaPath" TEXT,
        "signedIpaPath" TEXT,
        "manifestPath" TEXT,
        "installUrl" TEXT,
        "downloadUrl" TEXT,
        "errorCode" TEXT,
        "errorMessage" TEXT,
        "certificateFingerprint" TEXT,
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "startedAt" TIMESTAMP,
        "completedAt" TIMESTAMP,
        "expiresAt" TIMESTAMP,
        "cleanedAt" TIMESTAMP
      )
    `);

    await executeRaw(`
      CREATE INDEX IF NOT EXISTS idx_sign_tasks_user_createdAt
      ON sign_tasks ("userId", "createdAt" DESC)
    `);

    await executeRaw(`
      CREATE TABLE IF NOT EXISTS sign_certificates (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "ownerUserId" INTEGER,
        scope TEXT NOT NULL DEFAULT 'system',
        name TEXT NOT NULL,
        "fileName" TEXT NOT NULL,
        "filePath" TEXT NOT NULL,
        password TEXT NOT NULL,
        "subjectCn" TEXT,
        "teamId" TEXT,
        "isActive" INTEGER NOT NULL DEFAULT 0,
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await executeRaw(`
      CREATE TABLE IF NOT EXISTS sign_profiles (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "ownerUserId" INTEGER,
        scope TEXT NOT NULL DEFAULT 'system',
        name TEXT NOT NULL,
        "fileName" TEXT NOT NULL,
        "filePath" TEXT NOT NULL,
        note TEXT,
        "appId" TEXT,
        "teamId" TEXT,
        "profileUuid" TEXT,
        "isActive" INTEGER NOT NULL DEFAULT 0,
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await executeRaw(`
      CREATE TABLE IF NOT EXISTS sign_user_permissions (
        "userId" INTEGER PRIMARY KEY,
        "canSign" INTEGER NOT NULL DEFAULT 0,
        "canSelfSign" INTEGER NOT NULL DEFAULT 0,
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    return;
  }

  await executeRaw(`
    CREATE TABLE IF NOT EXISTS sign_devices (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      userId INTEGER NOT NULL,
      udid TEXT NOT NULL,
      product TEXT,
      version TEXT,
      deviceName TEXT,
      source TEXT DEFAULT 'profile_service',
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await executeRaw(`
    CREATE UNIQUE INDEX IF NOT EXISTS idx_sign_devices_user_udid
    ON sign_devices (userId, udid)
  `);

  await executeRaw(`
    CREATE TABLE IF NOT EXISTS sign_tasks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      userId INTEGER NOT NULL,
      deviceId INTEGER,
      certificateId INTEGER,
      profileId INTEGER,
      status TEXT NOT NULL DEFAULT 'queued',
      progress INTEGER NOT NULL DEFAULT 0,
      stage TEXT DEFAULT 'waiting',
      ipaName TEXT,
      ipaPath TEXT,
      signedIpaPath TEXT,
      manifestPath TEXT,
      installUrl TEXT,
      downloadUrl TEXT,
      errorCode TEXT,
      errorMessage TEXT,
      certificateFingerprint TEXT,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      startedAt DATETIME,
      completedAt DATETIME,
      expiresAt DATETIME,
      cleanedAt DATETIME
    )
  `);

  await executeRaw(`
    CREATE INDEX IF NOT EXISTS idx_sign_tasks_user_createdAt
    ON sign_tasks (userId, createdAt DESC)
  `);

  await executeRaw(`
    CREATE TABLE IF NOT EXISTS sign_certificates (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ownerUserId INTEGER,
      scope TEXT NOT NULL DEFAULT 'system',
      name TEXT NOT NULL,
      fileName TEXT NOT NULL,
      filePath TEXT NOT NULL,
      password TEXT NOT NULL,
      subjectCn TEXT,
      teamId TEXT,
      isActive INTEGER NOT NULL DEFAULT 0,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await executeRaw(`
    CREATE TABLE IF NOT EXISTS sign_profiles (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ownerUserId INTEGER,
      scope TEXT NOT NULL DEFAULT 'system',
      name TEXT NOT NULL,
      fileName TEXT NOT NULL,
      filePath TEXT NOT NULL,
      note TEXT,
      appId TEXT,
      teamId TEXT,
      profileUuid TEXT,
      isActive INTEGER NOT NULL DEFAULT 0,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await executeRaw(`
    CREATE TABLE IF NOT EXISTS sign_user_permissions (
      userId INTEGER PRIMARY KEY,
      canSign INTEGER NOT NULL DEFAULT 0,
      canSelfSign INTEGER NOT NULL DEFAULT 0,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
    )
  `);
}

export async function ensureSignTables() {
  if (ensured) {
    return;
  }

  await ensureBaseTables();

  await ensureColumn('sign_tasks', 'certificateId', 'INTEGER');
  await ensureColumn('sign_tasks', 'profileId', 'INTEGER');
  await ensureColumn('sign_tasks', 'expiresAt', 'DATETIME', 'TIMESTAMP');
  await ensureColumn('sign_tasks', 'cleanedAt', 'DATETIME', 'TIMESTAMP');

  await ensureColumn('sign_certificates', 'ownerUserId', 'INTEGER');
  await ensureColumn('sign_certificates', 'scope', "TEXT NOT NULL DEFAULT 'system'");

  await ensureColumn('sign_profiles', 'ownerUserId', 'INTEGER');
  await ensureColumn('sign_profiles', 'scope', "TEXT NOT NULL DEFAULT 'system'");

  ensured = true;
}
