
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  App: 'App',
  Post: 'Post',
  Topic: 'Topic',
  TopicApp: 'TopicApp',
  TopicPost: 'TopicPost',
  Comment: 'Comment',
  SoftwareRequest: 'SoftwareRequest',
  HotSearch: 'HotSearch'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  name: 'name',
  avatar: 'avatar',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AppScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  subtitle: 'subtitle',
  category: 'category',
  icon: 'icon',
  version: 'version',
  size: 'size',
  rating: 'rating',
  downloads: 'downloads',
  updatedAt: 'updatedAt',
  compatibility: 'compatibility',
  platforms: 'platforms',
  heroImage: 'heroImage',
  gallery: 'gallery',
  tags: 'tags',
  verified: 'verified',
  editorialScore: 'editorialScore',
  pricing: 'pricing',
  summary: 'summary',
  highlights: 'highlights',
  requirements: 'requirements',
  review: 'review',
  featured: 'featured',
  status: 'status',
  seoTitle: 'seoTitle',
  seoDescription: 'seoDescription',
  createdAt: 'createdAt',
  authorId: 'authorId'
} as const

export type AppScalarFieldEnum = (typeof AppScalarFieldEnum)[keyof typeof AppScalarFieldEnum]


export const PostScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  excerpt: 'excerpt',
  content: 'content',
  category: 'category',
  author: 'author',
  authorId: 'authorId',
  coverImage: 'coverImage',
  relatedAppSlug: 'relatedAppSlug',
  featured: 'featured',
  readingTime: 'readingTime',
  dateLabel: 'dateLabel',
  publishedAt: 'publishedAt',
  status: 'status',
  seoTitle: 'seoTitle',
  seoDescription: 'seoDescription',
  createdAt: 'createdAt'
} as const

export type PostScalarFieldEnum = (typeof PostScalarFieldEnum)[keyof typeof PostScalarFieldEnum]


export const TopicScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  description: 'description',
  coverImage: 'coverImage',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TopicScalarFieldEnum = (typeof TopicScalarFieldEnum)[keyof typeof TopicScalarFieldEnum]


export const TopicAppScalarFieldEnum = {
  topicId: 'topicId',
  appSlug: 'appSlug'
} as const

export type TopicAppScalarFieldEnum = (typeof TopicAppScalarFieldEnum)[keyof typeof TopicAppScalarFieldEnum]


export const TopicPostScalarFieldEnum = {
  topicId: 'topicId',
  postSlug: 'postSlug'
} as const

export type TopicPostScalarFieldEnum = (typeof TopicPostScalarFieldEnum)[keyof typeof TopicPostScalarFieldEnum]


export const CommentScalarFieldEnum = {
  id: 'id',
  contentId: 'contentId',
  contentType: 'contentType',
  authorName: 'authorName',
  authorAvatar: 'authorAvatar',
  content: 'content',
  parentId: 'parentId',
  createdAt: 'createdAt',
  likes: 'likes',
  dislikes: 'dislikes',
  appSlug: 'appSlug',
  postSlug: 'postSlug'
} as const

export type CommentScalarFieldEnum = (typeof CommentScalarFieldEnum)[keyof typeof CommentScalarFieldEnum]


export const SoftwareRequestScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  authorName: 'authorName',
  authorEmail: 'authorEmail',
  status: 'status',
  createdAt: 'createdAt',
  adminReply: 'adminReply',
  repliedAt: 'repliedAt'
} as const

export type SoftwareRequestScalarFieldEnum = (typeof SoftwareRequestScalarFieldEnum)[keyof typeof SoftwareRequestScalarFieldEnum]


export const HotSearchScalarFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  type: 'type',
  count: 'count'
} as const

export type HotSearchScalarFieldEnum = (typeof HotSearchScalarFieldEnum)[keyof typeof HotSearchScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

